/*
Conekta API

Testing ShippingContactsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package conekta

import (
	"context"
	"testing"

	openapiclient "github.com/conekta/conekta-go/v7"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_conekta_ShippingContactsAPIService(t *testing.T) {

	apiClient := testClient()

	t.Run("Test ShippingContactsAPIService CreateCustomerShippingContacts", func(t *testing.T) {

		id := "cus_2tXyF9BwPG14UMkkg"

		resp, httpRes, err := apiClient.ShippingContactsAPI.CreateCustomerShippingContacts(context.Background(), id).CustomerShippingContactsRequest(openapiclient.CustomerShippingContactsRequest{}).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShippingContactsAPIService DeleteCustomerShippingContacts", func(t *testing.T) {

		id := "cus_2tZWxbTPtQgGJGh8P"
		shippingContactsId := "ship_cont_2tZWzJPBf87C6TcoQ"

		resp, httpRes, err := apiClient.ShippingContactsAPI.DeleteCustomerShippingContacts(context.Background(), id, shippingContactsId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShippingContactsAPIService UpdateCustomerShippingContacts", func(t *testing.T) {

		id := "cus_2tZWxbTPtQgGJGh8P"
		shippingContactsId := "ship_cont_2tZWzJPBf87C6TcoQ"

		resp, httpRes, err := apiClient.ShippingContactsAPI.UpdateCustomerShippingContacts(context.Background(), id, shippingContactsId).CustomerUpdateShippingContactsRequest(openapiclient.CustomerUpdateShippingContactsRequest{}).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
