/*
Conekta API

Testing TransfersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package conekta

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_conekta_TransfersAPIService(t *testing.T) {

	apiClient := testClient()

	t.Run("Test TransfersAPIService GetTransfer", func(t *testing.T) {

		id := "64462930651b2600017b6d43"

		resp, httpRes, err := apiClient.TransfersAPI.GetTransfer(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransfersAPIService GetTransfers", func(t *testing.T) {

		resp, httpRes, err := apiClient.TransfersAPI.GetTransfers(context.Background()).Limit(5).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
