/*
Conekta API

Testing LogsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package conekta

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_conekta_LogsAPIService(t *testing.T) {

	apiClient := testClient()

	t.Run("Test LogsAPIService GetLogById", func(t *testing.T) {

		id := "6419dd15b985080001fc280e"

		resp, httpRes, err := apiClient.LogsAPI.GetLogById(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LogsAPIService GetLogs", func(t *testing.T) {

		resp, httpRes, err := apiClient.LogsAPI.GetLogs(context.Background()).Limit(20).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
