/*
Conekta API

Testing ChargesApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package conekta_test

import (
	"context"
	"testing"

	"github.com/conekta/conekta-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_conekta_ChargesApiService(t *testing.T) {

	configuration := conekta.NewConfiguration()
	configuration.Host = _basePath
	configuration.Scheme = "http"
	apiClient := conekta.NewAPIClient(configuration)

	t.Run("Test ChargesApiService GetCharges", func(t *testing.T) {
		resp, httpRes, err := apiClient.ChargesApi.GetCharges(context.TODO()).
			Limit(20).
			AcceptLanguage("es").
			Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChargesApiService OrdersCreateCharge", func(t *testing.T) {
		req := conekta.ChargeRequest{
			Amount: conekta.PtrInt32(1000),
		}
		resp, httpRes, err := apiClient.ChargesApi.OrdersCreateCharge(context.TODO(), "ord_2tUigJ8DgBhbp6w5D").
			ChargeRequest(req).
			AcceptLanguage("es").
			Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
