/*
Conekta API

Testing TokensAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package conekta

import (
	"context"
	"testing"

	openapiclient "github.com/conekta/conekta-go/v7"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_conekta_TokensAPIService(t *testing.T) {

	apiClient := testClient()

	t.Run("Test TokensAPIService CreateToken", func(t *testing.T) {

		resp, httpRes, err := apiClient.TokensAPI.CreateToken(context.Background()).TokenRequest(openapiclient.TokenRequest{Card: &openapiclient.TokenRequestCard{Number: "5475040095304607", Name: "Test", ExpMonth: "12", ExpYear: "30", Cvc: "123"}}).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
