/*
Conekta API

Testing EventsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package conekta

import (
	"context"
	"testing"

	openapiclient "github.com/conekta/conekta-go/v8"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_conekta_EventsAPIService(t *testing.T) {

	apiClient := testClient()

	t.Run("Test EventsAPIService GetEvent", func(t *testing.T) {

		id := "63fe3d2ddf70970001cfb41a"

		resp, httpRes, err := apiClient.EventsAPI.GetEvent(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EventsAPIService GetEvents", func(t *testing.T) {

		resp, httpRes, err := apiClient.EventsAPI.GetEvents(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EventsAPIService ResendEvent", func(t *testing.T) {

		eventId := "6463d6e35a4c3e001819e761"

		resp, httpRes, err := apiClient.EventsAPI.ResendEvent(context.Background(), eventId).ResendEventRequest(openapiclient.ResendEventRequest{}).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
