/*
Conekta API

Testing ShippingsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package conekta

import (
	"context"
	"testing"

	openapiclient "github.com/conekta/conekta-go/v8"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_conekta_ShippingsAPIService(t *testing.T) {

	apiClient := testClient()

	t.Run("Test ShippingsAPIService OrdersCreateShipping", func(t *testing.T) {

		id := "ord_2tVyWPnCPWbrV37mW"

		resp, httpRes, err := apiClient.ShippingsAPI.OrdersCreateShipping(context.Background(), id).ShippingRequest(openapiclient.ShippingRequest{}).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShippingsAPIService OrdersDeleteShipping", func(t *testing.T) {

		id := "ord_2tVyWPnCPWbrV37mW"
		shippingId := "ship_lin_2tVzNuDGSaDwreMg6"

		resp, httpRes, err := apiClient.ShippingsAPI.OrdersDeleteShipping(context.Background(), id, shippingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShippingsAPIService OrdersUpdateShipping", func(t *testing.T) {

		id := "ord_2tVyWPnCPWbrV37mW"
		shippingId := "ship_lin_2tVzNuDGSaDwreMg6"

		resp, httpRes, err := apiClient.ShippingsAPI.OrdersUpdateShipping(context.Background(), id, shippingId).ShippingRequest(openapiclient.ShippingRequest{}).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
