/*
Conekta API

Testing PaymentMethodsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package conekta_test

import (
	"context"
	"testing"

	"github.com/conekta/conekta-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_conekta_PaymentMethodsApiService(t *testing.T) {

	configuration := conekta.NewConfiguration()
	configuration.Host = _basePath
	configuration.Scheme = "http"
	apiClient := conekta.NewAPIClient(configuration)

	t.Run("Test PaymentMethodsApiService CreateCustomerPaymentMethods", func(t *testing.T) {
		req := conekta.CreateCustomerPaymentMethodsRequest{
			PaymentMethodCardRequest: &conekta.PaymentMethodCardRequest{
				Type:    "oxxo_recurrent",
				TokenId: "tokenID",
			},
		}
		resp, httpRes, err := apiClient.PaymentMethodsApi.CreateCustomerPaymentMethods(context.TODO(), "cus_2tXyF9BwPG14UMkkg").
			CreateCustomerPaymentMethodsRequest(req).
			AcceptLanguage("es").
			Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PaymentMethodsApiService DeleteCustomerPaymentMethods", func(t *testing.T) {
		resp, httpRes, err := apiClient.PaymentMethodsApi.DeleteCustomerPaymentMethods(context.TODO(), "cus_2tYENskzTjjgkGQLt", "src_2tbd5Bgy67RL9oycM").
			AcceptLanguage("es").
			Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PaymentMethodsApiService GetCustomerPaymentMethods", func(t *testing.T) {
		resp, httpRes, err := apiClient.PaymentMethodsApi.GetCustomerPaymentMethods(context.TODO(), "cus_2tYENskzTjjgkGQLt").
			AcceptLanguage("es").
			Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PaymentMethodsApiService UpdateCustomerPaymentMethods", func(t *testing.T) {
		req := conekta.UpdatePaymentMethods{
			Name: conekta.PtrString("name"),
		}
		resp, httpRes, err := apiClient.PaymentMethodsApi.UpdateCustomerPaymentMethods(context.TODO(), "cus_2tYENskzTjjgkGQLt", "src_2tbd5Bgy67RL9oycM").
			UpdatePaymentMethods(req).
			AcceptLanguage("es").
			Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
