/*
Conekta API

Testing WebhooksAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package conekta

import (
	"context"
	"testing"

	openapiclient "github.com/conekta/conekta-go/v7"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_conekta_WebhooksAPIService(t *testing.T) {

	apiClient := testClient()

	t.Run("Test WebhooksAPIService CreateWebhook", func(t *testing.T) {

		resp, httpRes, err := apiClient.WebhooksAPI.CreateWebhook(context.Background()).WebhookRequest(openapiclient.WebhookRequest{Url: "https://webhook.site/0b8c9fa8-92c3-4a04-beea-a7ec037f6466"}).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhooksAPIService DeleteWebhook", func(t *testing.T) {

		id := "641b1d5662d7e00001eaa46b"

		resp, httpRes, err := apiClient.WebhooksAPI.DeleteWebhook(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhooksAPIService GetWebhook", func(t *testing.T) {

		id := "641b1d5662d7e00001eaa46b"

		resp, httpRes, err := apiClient.WebhooksAPI.GetWebhook(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhooksAPIService GetWebhooks", func(t *testing.T) {

		resp, httpRes, err := apiClient.WebhooksAPI.GetWebhooks(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhooksAPIService TestWebhook", func(t *testing.T) {

		id := "641b1d5662d7e00001eaa46b"

		resp, httpRes, err := apiClient.WebhooksAPI.TestWebhook(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhooksAPIService UpdateWebhook", func(t *testing.T) {

		id := "641b1d5662d7e00001eaa46b"

		resp, httpRes, err := apiClient.WebhooksAPI.UpdateWebhook(context.Background(), id).UpdateWebhook(openapiclient.UpdateWebhook{}).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
