/*
Conekta API

Testing PayoutOrdersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package conekta

import (
	"context"
	"testing"

	openapiclient "github.com/conekta/conekta-go/v7"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_conekta_PayoutOrdersAPIService(t *testing.T) {

	apiClient := testClient()

	t.Run("Test PayoutOrdersAPIService CancelPayoutOrderById", func(t *testing.T) {

		t.Skip("mock server (conekta_api.json) does not implement the cancel payout order endpoint")

		id := "f2654d66-d740-457a-9a8c-f96b5196f44e"

		resp, httpRes, err := apiClient.PayoutOrdersAPI.CancelPayoutOrderById(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PayoutOrdersAPIService CreatePayoutOrder", func(t *testing.T) {

		resp, httpRes, err := apiClient.PayoutOrdersAPI.CreatePayoutOrder(context.Background()).PayoutOrderRequest(openapiclient.PayoutOrderRequest{Amount: 3000}).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PayoutOrdersAPIService GetPayoutOrderById", func(t *testing.T) {

		id := "f2654d66-d740-457a-9a8c-f96b5196f44e"

		resp, httpRes, err := apiClient.PayoutOrdersAPI.GetPayoutOrderById(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PayoutOrdersAPIService GetPayoutOrders", func(t *testing.T) {

		resp, httpRes, err := apiClient.PayoutOrdersAPI.GetPayoutOrders(context.Background()).AcceptLanguage("es").Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
