/*
Conekta API

Testing DiscountsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package conekta

import (
	"context"
	"testing"

	openapiclient "github.com/conekta/conekta-go/v7"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_conekta_DiscountsAPIService(t *testing.T) {

	apiClient := testClient()

	t.Run("Test DiscountsAPIService OrdersCreateDiscountLine", func(t *testing.T) {

		id := "ord_2tVyWPnCPWbrV37mW"

		resp, httpRes, err := apiClient.DiscountsAPI.OrdersCreateDiscountLine(context.Background(), id).OrderDiscountLinesRequest(openapiclient.OrderDiscountLinesRequest{}).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DiscountsAPIService OrdersDeleteDiscountLines", func(t *testing.T) {

		id := "ord_2tVyWPnCPWbrV37mW"
		discountLinesId := "dis_lin_2tVyahK8Nts7rKRMZ"

		resp, httpRes, err := apiClient.DiscountsAPI.OrdersDeleteDiscountLines(context.Background(), id, discountLinesId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DiscountsAPIService OrdersGetDiscountLine", func(t *testing.T) {

		id := "ord_2tkwrBmcvGnA9zdU9"
		discountLinesId := "dis_lin_2tkwrBmcvGnA9zdU6"

		resp, httpRes, err := apiClient.DiscountsAPI.OrdersGetDiscountLine(context.Background(), id, discountLinesId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DiscountsAPIService OrdersGetDiscountLines", func(t *testing.T) {

		id := "ord_2tVyWPnCPWbrV37mW"

		resp, httpRes, err := apiClient.DiscountsAPI.OrdersGetDiscountLines(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DiscountsAPIService OrdersUpdateDiscountLines", func(t *testing.T) {

		id := "ord_2tVyWPnCPWbrV37mW"
		discountLinesId := "dis_lin_2tVyahK8Nts7rKRMZ"

		resp, httpRes, err := apiClient.DiscountsAPI.OrdersUpdateDiscountLines(context.Background(), id, discountLinesId).UpdateOrderDiscountLinesRequest(openapiclient.UpdateOrderDiscountLinesRequest{}).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
