/*
Conekta API

Conekta sdk

API version: 2.2.0
Contact: engineering@conekta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conekta

import (
	"encoding/json"
	"fmt"
)

// OrderUpdateCustomerInfo - struct for OrderUpdateCustomerInfo
type OrderUpdateCustomerInfo struct {
	CustomerInfo *CustomerInfo
	CustomerInfoCustomerId *CustomerInfoCustomerId
}

// CustomerInfoAsOrderUpdateCustomerInfo is a convenience function that returns CustomerInfo wrapped in OrderUpdateCustomerInfo
func CustomerInfoAsOrderUpdateCustomerInfo(v *CustomerInfo) OrderUpdateCustomerInfo {
	return OrderUpdateCustomerInfo{
		CustomerInfo: v,
	}
}

// CustomerInfoCustomerIdAsOrderUpdateCustomerInfo is a convenience function that returns CustomerInfoCustomerId wrapped in OrderUpdateCustomerInfo
func CustomerInfoCustomerIdAsOrderUpdateCustomerInfo(v *CustomerInfoCustomerId) OrderUpdateCustomerInfo {
	return OrderUpdateCustomerInfo{
		CustomerInfoCustomerId: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *OrderUpdateCustomerInfo) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CustomerInfo
	err = json.Unmarshal(data, &dst.CustomerInfo)
	if err == nil {
		jsonCustomerInfo, _ := json.Marshal(dst.CustomerInfo)
		if string(jsonCustomerInfo) == "{}" { // empty struct
			dst.CustomerInfo = nil
		} else {
			match++
		}
	} else {
		dst.CustomerInfo = nil
	}

	// try to unmarshal data into CustomerInfoCustomerId
	err = json.Unmarshal(data, &dst.CustomerInfoCustomerId)
	if err == nil {
		jsonCustomerInfoCustomerId, _ := json.Marshal(dst.CustomerInfoCustomerId)
		if string(jsonCustomerInfoCustomerId) == "{}" { // empty struct
			dst.CustomerInfoCustomerId = nil
		} else {
			match++
		}
	} else {
		dst.CustomerInfoCustomerId = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CustomerInfo = nil
		dst.CustomerInfoCustomerId = nil

		return fmt.Errorf("data matches more than one schema in oneOf(OrderUpdateCustomerInfo)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(OrderUpdateCustomerInfo)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src OrderUpdateCustomerInfo) MarshalJSON() ([]byte, error) {
	if src.CustomerInfo != nil {
		return json.Marshal(&src.CustomerInfo)
	}

	if src.CustomerInfoCustomerId != nil {
		return json.Marshal(&src.CustomerInfoCustomerId)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *OrderUpdateCustomerInfo) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CustomerInfo != nil {
		return obj.CustomerInfo
	}

	if obj.CustomerInfoCustomerId != nil {
		return obj.CustomerInfoCustomerId
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj OrderUpdateCustomerInfo) GetActualInstanceValue() (interface{}) {
	if obj.CustomerInfo != nil {
		return *obj.CustomerInfo
	}

	if obj.CustomerInfoCustomerId != nil {
		return *obj.CustomerInfoCustomerId
	}

	// all schemas are nil
	return nil
}

type NullableOrderUpdateCustomerInfo struct {
	value *OrderUpdateCustomerInfo
	isSet bool
}

func (v NullableOrderUpdateCustomerInfo) Get() *OrderUpdateCustomerInfo {
	return v.value
}

func (v *NullableOrderUpdateCustomerInfo) Set(val *OrderUpdateCustomerInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderUpdateCustomerInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderUpdateCustomerInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderUpdateCustomerInfo(val *OrderUpdateCustomerInfo) *NullableOrderUpdateCustomerInfo {
	return &NullableOrderUpdateCustomerInfo{value: val, isSet: true}
}

func (v NullableOrderUpdateCustomerInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderUpdateCustomerInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


