/*
Conekta API

Conekta sdk

API version: 2.2.0
Contact: engineering@conekta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conekta

import (
	"encoding/json"
)

// checks if the OrderUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderUpdate{}

// OrderUpdate a order
type OrderUpdate struct {
	Charges []ChargeRequest `json:"charges,omitempty"`
	Checkout *OrderCheckoutRequest `json:"checkout,omitempty"`
	// Currency with which the payment will be made. It uses the 3-letter code of the [International Standard ISO 4217.](https://es.wikipedia.org/wiki/ISO_4217)
	Currency *string `json:"currency,omitempty"`
	CustomerInfo *OrderUpdateCustomerInfo `json:"customer_info,omitempty"`
	// List of [discounts](https://developers.conekta.com/v2.2.0/reference/orderscreatediscountline) that are applied to the order.
	DiscountLines []OrderDiscountLinesRequest `json:"discount_lines,omitempty"`
	FiscalEntity *OrderUpdateFiscalEntityRequest `json:"fiscal_entity,omitempty"`
	// List of [products](https://developers.conekta.com/v2.2.0/reference/orderscreateproduct) that are sold in the order. You must have at least one product.
	LineItems []Product `json:"line_items,omitempty"`
	Metadata map[string]string `json:"metadata,omitempty"`
	// Indicates whether the order charges must be preauthorized
	PreAuthorize *bool `json:"pre_authorize,omitempty"`
	ShippingContact *CustomerShippingContactsRequest `json:"shipping_contact,omitempty"`
	// List of [shipping costs](https://developers.conekta.com/v2.2.0/reference/orderscreateshipping). If the online store offers digital products.
	ShippingLines []ShippingRequest `json:"shipping_lines,omitempty"`
	TaxLines []OrderTaxRequest `json:"tax_lines,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OrderUpdate OrderUpdate

// NewOrderUpdate instantiates a new OrderUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderUpdate() *OrderUpdate {
	this := OrderUpdate{}
	return &this
}

// NewOrderUpdateWithDefaults instantiates a new OrderUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderUpdateWithDefaults() *OrderUpdate {
	this := OrderUpdate{}
	return &this
}

// GetCharges returns the Charges field value if set, zero value otherwise.
func (o *OrderUpdate) GetCharges() []ChargeRequest {
	if o == nil || IsNil(o.Charges) {
		var ret []ChargeRequest
		return ret
	}
	return o.Charges
}

// GetChargesOk returns a tuple with the Charges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderUpdate) GetChargesOk() ([]ChargeRequest, bool) {
	if o == nil || IsNil(o.Charges) {
		return nil, false
	}
	return o.Charges, true
}

// HasCharges returns a boolean if a field has been set.
func (o *OrderUpdate) HasCharges() bool {
	if o != nil && !IsNil(o.Charges) {
		return true
	}

	return false
}

// SetCharges gets a reference to the given []ChargeRequest and assigns it to the Charges field.
func (o *OrderUpdate) SetCharges(v []ChargeRequest) {
	o.Charges = v
}

// GetCheckout returns the Checkout field value if set, zero value otherwise.
func (o *OrderUpdate) GetCheckout() OrderCheckoutRequest {
	if o == nil || IsNil(o.Checkout) {
		var ret OrderCheckoutRequest
		return ret
	}
	return *o.Checkout
}

// GetCheckoutOk returns a tuple with the Checkout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderUpdate) GetCheckoutOk() (*OrderCheckoutRequest, bool) {
	if o == nil || IsNil(o.Checkout) {
		return nil, false
	}
	return o.Checkout, true
}

// HasCheckout returns a boolean if a field has been set.
func (o *OrderUpdate) HasCheckout() bool {
	if o != nil && !IsNil(o.Checkout) {
		return true
	}

	return false
}

// SetCheckout gets a reference to the given OrderCheckoutRequest and assigns it to the Checkout field.
func (o *OrderUpdate) SetCheckout(v OrderCheckoutRequest) {
	o.Checkout = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *OrderUpdate) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderUpdate) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *OrderUpdate) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *OrderUpdate) SetCurrency(v string) {
	o.Currency = &v
}

// GetCustomerInfo returns the CustomerInfo field value if set, zero value otherwise.
func (o *OrderUpdate) GetCustomerInfo() OrderUpdateCustomerInfo {
	if o == nil || IsNil(o.CustomerInfo) {
		var ret OrderUpdateCustomerInfo
		return ret
	}
	return *o.CustomerInfo
}

// GetCustomerInfoOk returns a tuple with the CustomerInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderUpdate) GetCustomerInfoOk() (*OrderUpdateCustomerInfo, bool) {
	if o == nil || IsNil(o.CustomerInfo) {
		return nil, false
	}
	return o.CustomerInfo, true
}

// HasCustomerInfo returns a boolean if a field has been set.
func (o *OrderUpdate) HasCustomerInfo() bool {
	if o != nil && !IsNil(o.CustomerInfo) {
		return true
	}

	return false
}

// SetCustomerInfo gets a reference to the given OrderUpdateCustomerInfo and assigns it to the CustomerInfo field.
func (o *OrderUpdate) SetCustomerInfo(v OrderUpdateCustomerInfo) {
	o.CustomerInfo = &v
}

// GetDiscountLines returns the DiscountLines field value if set, zero value otherwise.
func (o *OrderUpdate) GetDiscountLines() []OrderDiscountLinesRequest {
	if o == nil || IsNil(o.DiscountLines) {
		var ret []OrderDiscountLinesRequest
		return ret
	}
	return o.DiscountLines
}

// GetDiscountLinesOk returns a tuple with the DiscountLines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderUpdate) GetDiscountLinesOk() ([]OrderDiscountLinesRequest, bool) {
	if o == nil || IsNil(o.DiscountLines) {
		return nil, false
	}
	return o.DiscountLines, true
}

// HasDiscountLines returns a boolean if a field has been set.
func (o *OrderUpdate) HasDiscountLines() bool {
	if o != nil && !IsNil(o.DiscountLines) {
		return true
	}

	return false
}

// SetDiscountLines gets a reference to the given []OrderDiscountLinesRequest and assigns it to the DiscountLines field.
func (o *OrderUpdate) SetDiscountLines(v []OrderDiscountLinesRequest) {
	o.DiscountLines = v
}

// GetFiscalEntity returns the FiscalEntity field value if set, zero value otherwise.
func (o *OrderUpdate) GetFiscalEntity() OrderUpdateFiscalEntityRequest {
	if o == nil || IsNil(o.FiscalEntity) {
		var ret OrderUpdateFiscalEntityRequest
		return ret
	}
	return *o.FiscalEntity
}

// GetFiscalEntityOk returns a tuple with the FiscalEntity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderUpdate) GetFiscalEntityOk() (*OrderUpdateFiscalEntityRequest, bool) {
	if o == nil || IsNil(o.FiscalEntity) {
		return nil, false
	}
	return o.FiscalEntity, true
}

// HasFiscalEntity returns a boolean if a field has been set.
func (o *OrderUpdate) HasFiscalEntity() bool {
	if o != nil && !IsNil(o.FiscalEntity) {
		return true
	}

	return false
}

// SetFiscalEntity gets a reference to the given OrderUpdateFiscalEntityRequest and assigns it to the FiscalEntity field.
func (o *OrderUpdate) SetFiscalEntity(v OrderUpdateFiscalEntityRequest) {
	o.FiscalEntity = &v
}

// GetLineItems returns the LineItems field value if set, zero value otherwise.
func (o *OrderUpdate) GetLineItems() []Product {
	if o == nil || IsNil(o.LineItems) {
		var ret []Product
		return ret
	}
	return o.LineItems
}

// GetLineItemsOk returns a tuple with the LineItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderUpdate) GetLineItemsOk() ([]Product, bool) {
	if o == nil || IsNil(o.LineItems) {
		return nil, false
	}
	return o.LineItems, true
}

// HasLineItems returns a boolean if a field has been set.
func (o *OrderUpdate) HasLineItems() bool {
	if o != nil && !IsNil(o.LineItems) {
		return true
	}

	return false
}

// SetLineItems gets a reference to the given []Product and assigns it to the LineItems field.
func (o *OrderUpdate) SetLineItems(v []Product) {
	o.LineItems = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrderUpdate) GetMetadata() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrderUpdate) GetMetadataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return &o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *OrderUpdate) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *OrderUpdate) SetMetadata(v map[string]string) {
	o.Metadata = v
}

// GetPreAuthorize returns the PreAuthorize field value if set, zero value otherwise.
func (o *OrderUpdate) GetPreAuthorize() bool {
	if o == nil || IsNil(o.PreAuthorize) {
		var ret bool
		return ret
	}
	return *o.PreAuthorize
}

// GetPreAuthorizeOk returns a tuple with the PreAuthorize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderUpdate) GetPreAuthorizeOk() (*bool, bool) {
	if o == nil || IsNil(o.PreAuthorize) {
		return nil, false
	}
	return o.PreAuthorize, true
}

// HasPreAuthorize returns a boolean if a field has been set.
func (o *OrderUpdate) HasPreAuthorize() bool {
	if o != nil && !IsNil(o.PreAuthorize) {
		return true
	}

	return false
}

// SetPreAuthorize gets a reference to the given bool and assigns it to the PreAuthorize field.
func (o *OrderUpdate) SetPreAuthorize(v bool) {
	o.PreAuthorize = &v
}

// GetShippingContact returns the ShippingContact field value if set, zero value otherwise.
func (o *OrderUpdate) GetShippingContact() CustomerShippingContactsRequest {
	if o == nil || IsNil(o.ShippingContact) {
		var ret CustomerShippingContactsRequest
		return ret
	}
	return *o.ShippingContact
}

// GetShippingContactOk returns a tuple with the ShippingContact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderUpdate) GetShippingContactOk() (*CustomerShippingContactsRequest, bool) {
	if o == nil || IsNil(o.ShippingContact) {
		return nil, false
	}
	return o.ShippingContact, true
}

// HasShippingContact returns a boolean if a field has been set.
func (o *OrderUpdate) HasShippingContact() bool {
	if o != nil && !IsNil(o.ShippingContact) {
		return true
	}

	return false
}

// SetShippingContact gets a reference to the given CustomerShippingContactsRequest and assigns it to the ShippingContact field.
func (o *OrderUpdate) SetShippingContact(v CustomerShippingContactsRequest) {
	o.ShippingContact = &v
}

// GetShippingLines returns the ShippingLines field value if set, zero value otherwise.
func (o *OrderUpdate) GetShippingLines() []ShippingRequest {
	if o == nil || IsNil(o.ShippingLines) {
		var ret []ShippingRequest
		return ret
	}
	return o.ShippingLines
}

// GetShippingLinesOk returns a tuple with the ShippingLines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderUpdate) GetShippingLinesOk() ([]ShippingRequest, bool) {
	if o == nil || IsNil(o.ShippingLines) {
		return nil, false
	}
	return o.ShippingLines, true
}

// HasShippingLines returns a boolean if a field has been set.
func (o *OrderUpdate) HasShippingLines() bool {
	if o != nil && !IsNil(o.ShippingLines) {
		return true
	}

	return false
}

// SetShippingLines gets a reference to the given []ShippingRequest and assigns it to the ShippingLines field.
func (o *OrderUpdate) SetShippingLines(v []ShippingRequest) {
	o.ShippingLines = v
}

// GetTaxLines returns the TaxLines field value if set, zero value otherwise.
func (o *OrderUpdate) GetTaxLines() []OrderTaxRequest {
	if o == nil || IsNil(o.TaxLines) {
		var ret []OrderTaxRequest
		return ret
	}
	return o.TaxLines
}

// GetTaxLinesOk returns a tuple with the TaxLines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderUpdate) GetTaxLinesOk() ([]OrderTaxRequest, bool) {
	if o == nil || IsNil(o.TaxLines) {
		return nil, false
	}
	return o.TaxLines, true
}

// HasTaxLines returns a boolean if a field has been set.
func (o *OrderUpdate) HasTaxLines() bool {
	if o != nil && !IsNil(o.TaxLines) {
		return true
	}

	return false
}

// SetTaxLines gets a reference to the given []OrderTaxRequest and assigns it to the TaxLines field.
func (o *OrderUpdate) SetTaxLines(v []OrderTaxRequest) {
	o.TaxLines = v
}

func (o OrderUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Charges) {
		toSerialize["charges"] = o.Charges
	}
	if !IsNil(o.Checkout) {
		toSerialize["checkout"] = o.Checkout
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.CustomerInfo) {
		toSerialize["customer_info"] = o.CustomerInfo
	}
	if !IsNil(o.DiscountLines) {
		toSerialize["discount_lines"] = o.DiscountLines
	}
	if !IsNil(o.FiscalEntity) {
		toSerialize["fiscal_entity"] = o.FiscalEntity
	}
	if !IsNil(o.LineItems) {
		toSerialize["line_items"] = o.LineItems
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.PreAuthorize) {
		toSerialize["pre_authorize"] = o.PreAuthorize
	}
	if !IsNil(o.ShippingContact) {
		toSerialize["shipping_contact"] = o.ShippingContact
	}
	if !IsNil(o.ShippingLines) {
		toSerialize["shipping_lines"] = o.ShippingLines
	}
	if !IsNil(o.TaxLines) {
		toSerialize["tax_lines"] = o.TaxLines
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OrderUpdate) UnmarshalJSON(data []byte) (err error) {
	varOrderUpdate := _OrderUpdate{}

	err = json.Unmarshal(data, &varOrderUpdate)

	if err != nil {
		return err
	}

	*o = OrderUpdate(varOrderUpdate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "charges")
		delete(additionalProperties, "checkout")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "customer_info")
		delete(additionalProperties, "discount_lines")
		delete(additionalProperties, "fiscal_entity")
		delete(additionalProperties, "line_items")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "pre_authorize")
		delete(additionalProperties, "shipping_contact")
		delete(additionalProperties, "shipping_lines")
		delete(additionalProperties, "tax_lines")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOrderUpdate struct {
	value *OrderUpdate
	isSet bool
}

func (v NullableOrderUpdate) Get() *OrderUpdate {
	return v.value
}

func (v *NullableOrderUpdate) Set(val *OrderUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderUpdate(val *OrderUpdate) *NullableOrderUpdate {
	return &NullableOrderUpdate{value: val, isSet: true}
}

func (v NullableOrderUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


