/*
Conekta API

Conekta sdk

API version: 2.3.0
Contact: engineering@conekta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conekta

import (
	"encoding/json"
	"fmt"
)

// checks if the CheckoutOrderTemplate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckoutOrderTemplate{}

// CheckoutOrderTemplate It maintains the attributes with which the order will be created when receiving a new payment.
type CheckoutOrderTemplate struct {
	// It is the currency in which the order will be created. It must be a valid ISO 4217 currency code.
	Currency string `json:"currency"`
	CustomerInfo *CheckoutOrderTemplateCustomerInfo `json:"customer_info,omitempty"`
	// They are the products to buy. Each contains the \"unit price\" and \"quantity\" parameters that are used to calculate the total amount of the order.
	LineItems []Product `json:"line_items"`
	// It is a set of key-value pairs that you can attach to the order. It can be used to store additional information about the order in a structured format.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// List of [taxes](https://developers.conekta.com/v2.3.0/reference/orderscreatetaxes) that are applied to the order.
	TaxLines []OrderTaxRequest `json:"tax_lines,omitempty"`
	// List of [discounts](https://developers.conekta.com/v2.3.0/reference/orderscreatediscountline) that are applied to the order.
	DiscountLines []OrderDiscountLinesRequest `json:"discount_lines,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CheckoutOrderTemplate CheckoutOrderTemplate

// NewCheckoutOrderTemplate instantiates a new CheckoutOrderTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckoutOrderTemplate(currency string, lineItems []Product) *CheckoutOrderTemplate {
	this := CheckoutOrderTemplate{}
	this.Currency = currency
	this.LineItems = lineItems
	return &this
}

// NewCheckoutOrderTemplateWithDefaults instantiates a new CheckoutOrderTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckoutOrderTemplateWithDefaults() *CheckoutOrderTemplate {
	this := CheckoutOrderTemplate{}
	return &this
}

// GetCurrency returns the Currency field value
func (o *CheckoutOrderTemplate) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *CheckoutOrderTemplate) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *CheckoutOrderTemplate) SetCurrency(v string) {
	o.Currency = v
}

// GetCustomerInfo returns the CustomerInfo field value if set, zero value otherwise.
func (o *CheckoutOrderTemplate) GetCustomerInfo() CheckoutOrderTemplateCustomerInfo {
	if o == nil || IsNil(o.CustomerInfo) {
		var ret CheckoutOrderTemplateCustomerInfo
		return ret
	}
	return *o.CustomerInfo
}

// GetCustomerInfoOk returns a tuple with the CustomerInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckoutOrderTemplate) GetCustomerInfoOk() (*CheckoutOrderTemplateCustomerInfo, bool) {
	if o == nil || IsNil(o.CustomerInfo) {
		return nil, false
	}
	return o.CustomerInfo, true
}

// HasCustomerInfo returns a boolean if a field has been set.
func (o *CheckoutOrderTemplate) HasCustomerInfo() bool {
	if o != nil && !IsNil(o.CustomerInfo) {
		return true
	}

	return false
}

// SetCustomerInfo gets a reference to the given CheckoutOrderTemplateCustomerInfo and assigns it to the CustomerInfo field.
func (o *CheckoutOrderTemplate) SetCustomerInfo(v CheckoutOrderTemplateCustomerInfo) {
	o.CustomerInfo = &v
}

// GetLineItems returns the LineItems field value
func (o *CheckoutOrderTemplate) GetLineItems() []Product {
	if o == nil {
		var ret []Product
		return ret
	}

	return o.LineItems
}

// GetLineItemsOk returns a tuple with the LineItems field value
// and a boolean to check if the value has been set.
func (o *CheckoutOrderTemplate) GetLineItemsOk() ([]Product, bool) {
	if o == nil {
		return nil, false
	}
	return o.LineItems, true
}

// SetLineItems sets field value
func (o *CheckoutOrderTemplate) SetLineItems(v []Product) {
	o.LineItems = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CheckoutOrderTemplate) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckoutOrderTemplate) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CheckoutOrderTemplate) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *CheckoutOrderTemplate) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetTaxLines returns the TaxLines field value if set, zero value otherwise.
func (o *CheckoutOrderTemplate) GetTaxLines() []OrderTaxRequest {
	if o == nil || IsNil(o.TaxLines) {
		var ret []OrderTaxRequest
		return ret
	}
	return o.TaxLines
}

// GetTaxLinesOk returns a tuple with the TaxLines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckoutOrderTemplate) GetTaxLinesOk() ([]OrderTaxRequest, bool) {
	if o == nil || IsNil(o.TaxLines) {
		return nil, false
	}
	return o.TaxLines, true
}

// HasTaxLines returns a boolean if a field has been set.
func (o *CheckoutOrderTemplate) HasTaxLines() bool {
	if o != nil && !IsNil(o.TaxLines) {
		return true
	}

	return false
}

// SetTaxLines gets a reference to the given []OrderTaxRequest and assigns it to the TaxLines field.
func (o *CheckoutOrderTemplate) SetTaxLines(v []OrderTaxRequest) {
	o.TaxLines = v
}

// GetDiscountLines returns the DiscountLines field value if set, zero value otherwise.
func (o *CheckoutOrderTemplate) GetDiscountLines() []OrderDiscountLinesRequest {
	if o == nil || IsNil(o.DiscountLines) {
		var ret []OrderDiscountLinesRequest
		return ret
	}
	return o.DiscountLines
}

// GetDiscountLinesOk returns a tuple with the DiscountLines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckoutOrderTemplate) GetDiscountLinesOk() ([]OrderDiscountLinesRequest, bool) {
	if o == nil || IsNil(o.DiscountLines) {
		return nil, false
	}
	return o.DiscountLines, true
}

// HasDiscountLines returns a boolean if a field has been set.
func (o *CheckoutOrderTemplate) HasDiscountLines() bool {
	if o != nil && !IsNil(o.DiscountLines) {
		return true
	}

	return false
}

// SetDiscountLines gets a reference to the given []OrderDiscountLinesRequest and assigns it to the DiscountLines field.
func (o *CheckoutOrderTemplate) SetDiscountLines(v []OrderDiscountLinesRequest) {
	o.DiscountLines = v
}

func (o CheckoutOrderTemplate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckoutOrderTemplate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["currency"] = o.Currency
	if !IsNil(o.CustomerInfo) {
		toSerialize["customer_info"] = o.CustomerInfo
	}
	toSerialize["line_items"] = o.LineItems
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.TaxLines) {
		toSerialize["tax_lines"] = o.TaxLines
	}
	if !IsNil(o.DiscountLines) {
		toSerialize["discount_lines"] = o.DiscountLines
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CheckoutOrderTemplate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"currency",
		"line_items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckoutOrderTemplate := _CheckoutOrderTemplate{}

	err = json.Unmarshal(data, &varCheckoutOrderTemplate)

	if err != nil {
		return err
	}

	*o = CheckoutOrderTemplate(varCheckoutOrderTemplate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "currency")
		delete(additionalProperties, "customer_info")
		delete(additionalProperties, "line_items")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "tax_lines")
		delete(additionalProperties, "discount_lines")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCheckoutOrderTemplate struct {
	value *CheckoutOrderTemplate
	isSet bool
}

func (v NullableCheckoutOrderTemplate) Get() *CheckoutOrderTemplate {
	return v.value
}

func (v *NullableCheckoutOrderTemplate) Set(val *CheckoutOrderTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckoutOrderTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckoutOrderTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckoutOrderTemplate(val *CheckoutOrderTemplate) *NullableCheckoutOrderTemplate {
	return &NullableCheckoutOrderTemplate{value: val, isSet: true}
}

func (v NullableCheckoutOrderTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckoutOrderTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


