/*
Conekta API

Conekta sdk

API version: 2.3.0
Contact: engineering@conekta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conekta

import (
	"encoding/json"
)

// checks if the OrderCheckoutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderCheckoutRequest{}

// OrderCheckoutRequest [Checkout](https://developers.conekta.com/v2.3.0/reference/payment-link) details 
type OrderCheckoutRequest struct {
	// Are the payment methods available for this link. For subscriptions, only 'card' is allowed due to the recurring nature of the payments. This field is mutually exclusive with excluded_payment_methods.
	AllowedPaymentMethods []string `json:"allowed_payment_methods,omitempty"`
	// Payment methods to be excluded from the checkout. This field is mutually exclusive with allowed_payment_methods.
	ExcludedPaymentMethods []string `json:"excluded_payment_methods,omitempty"`
	// List of card networks to exclude from the checkout. This field is only applicable for card payments.
	ExcludeCardNetworks []string `json:"exclude_card_networks,omitempty"`
	// List of plan IDs that will be available for subscription. This field is required for subscription payments.
	PlanIds []string `json:"plan_ids,omitempty"`
	// It is the time when the link will expire.  It is expressed in seconds since the Unix epoch. The valid range is from 5 minutes to 365 days from the creation date. 
	ExpiresAt *int64 `json:"expires_at,omitempty"`
	// Redirection url back to the site in case of failed payment, applies only to HostedPayment.
	FailureUrl *string `json:"failure_url,omitempty"`
	// Indicates whether the card used for the payment should be saved for future purchases. This field is only applicable for card payments.
	ForceSaveCard *bool `json:"force_save_card,omitempty"`
	MonthlyInstallmentsEnabled *bool `json:"monthly_installments_enabled,omitempty"`
	MonthlyInstallmentsOptions []int32 `json:"monthly_installments_options,omitempty"`
	// Number of retries allowed before the checkout is marked as failed
	MaxFailedRetries *int32 `json:"max_failed_retries,omitempty"`
	// Reason for payment
	Name *string `json:"name,omitempty"`
	OnDemandEnabled *bool `json:"on_demand_enabled,omitempty"`
	// number of seconds to wait before redirecting to the success_url
	RedirectionTime *int32 `json:"redirection_time,omitempty"`
	// Redirection url back to the site in case of successful payment, applies only to HostedPayment
	SuccessUrl *string `json:"success_url,omitempty"`
	// Required. This field represents the type of checkout, which determines the user experience during the payment process. 'HostedPayment' will redirect the customer to a Conekta-hosted page to complete the payment, while 'Integration' allows the payment process to be handled entirely on your site using Conekta's APIs and SDKs.
	Type *string `json:"type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OrderCheckoutRequest OrderCheckoutRequest

// NewOrderCheckoutRequest instantiates a new OrderCheckoutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderCheckoutRequest() *OrderCheckoutRequest {
	this := OrderCheckoutRequest{}
	return &this
}

// NewOrderCheckoutRequestWithDefaults instantiates a new OrderCheckoutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderCheckoutRequestWithDefaults() *OrderCheckoutRequest {
	this := OrderCheckoutRequest{}
	return &this
}

// GetAllowedPaymentMethods returns the AllowedPaymentMethods field value if set, zero value otherwise.
func (o *OrderCheckoutRequest) GetAllowedPaymentMethods() []string {
	if o == nil || IsNil(o.AllowedPaymentMethods) {
		var ret []string
		return ret
	}
	return o.AllowedPaymentMethods
}

// GetAllowedPaymentMethodsOk returns a tuple with the AllowedPaymentMethods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCheckoutRequest) GetAllowedPaymentMethodsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedPaymentMethods) {
		return nil, false
	}
	return o.AllowedPaymentMethods, true
}

// HasAllowedPaymentMethods returns a boolean if a field has been set.
func (o *OrderCheckoutRequest) HasAllowedPaymentMethods() bool {
	if o != nil && !IsNil(o.AllowedPaymentMethods) {
		return true
	}

	return false
}

// SetAllowedPaymentMethods gets a reference to the given []string and assigns it to the AllowedPaymentMethods field.
func (o *OrderCheckoutRequest) SetAllowedPaymentMethods(v []string) {
	o.AllowedPaymentMethods = v
}

// GetExcludedPaymentMethods returns the ExcludedPaymentMethods field value if set, zero value otherwise.
func (o *OrderCheckoutRequest) GetExcludedPaymentMethods() []string {
	if o == nil || IsNil(o.ExcludedPaymentMethods) {
		var ret []string
		return ret
	}
	return o.ExcludedPaymentMethods
}

// GetExcludedPaymentMethodsOk returns a tuple with the ExcludedPaymentMethods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCheckoutRequest) GetExcludedPaymentMethodsOk() ([]string, bool) {
	if o == nil || IsNil(o.ExcludedPaymentMethods) {
		return nil, false
	}
	return o.ExcludedPaymentMethods, true
}

// HasExcludedPaymentMethods returns a boolean if a field has been set.
func (o *OrderCheckoutRequest) HasExcludedPaymentMethods() bool {
	if o != nil && !IsNil(o.ExcludedPaymentMethods) {
		return true
	}

	return false
}

// SetExcludedPaymentMethods gets a reference to the given []string and assigns it to the ExcludedPaymentMethods field.
func (o *OrderCheckoutRequest) SetExcludedPaymentMethods(v []string) {
	o.ExcludedPaymentMethods = v
}

// GetExcludeCardNetworks returns the ExcludeCardNetworks field value if set, zero value otherwise.
func (o *OrderCheckoutRequest) GetExcludeCardNetworks() []string {
	if o == nil || IsNil(o.ExcludeCardNetworks) {
		var ret []string
		return ret
	}
	return o.ExcludeCardNetworks
}

// GetExcludeCardNetworksOk returns a tuple with the ExcludeCardNetworks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCheckoutRequest) GetExcludeCardNetworksOk() ([]string, bool) {
	if o == nil || IsNil(o.ExcludeCardNetworks) {
		return nil, false
	}
	return o.ExcludeCardNetworks, true
}

// HasExcludeCardNetworks returns a boolean if a field has been set.
func (o *OrderCheckoutRequest) HasExcludeCardNetworks() bool {
	if o != nil && !IsNil(o.ExcludeCardNetworks) {
		return true
	}

	return false
}

// SetExcludeCardNetworks gets a reference to the given []string and assigns it to the ExcludeCardNetworks field.
func (o *OrderCheckoutRequest) SetExcludeCardNetworks(v []string) {
	o.ExcludeCardNetworks = v
}

// GetPlanIds returns the PlanIds field value if set, zero value otherwise.
func (o *OrderCheckoutRequest) GetPlanIds() []string {
	if o == nil || IsNil(o.PlanIds) {
		var ret []string
		return ret
	}
	return o.PlanIds
}

// GetPlanIdsOk returns a tuple with the PlanIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCheckoutRequest) GetPlanIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.PlanIds) {
		return nil, false
	}
	return o.PlanIds, true
}

// HasPlanIds returns a boolean if a field has been set.
func (o *OrderCheckoutRequest) HasPlanIds() bool {
	if o != nil && !IsNil(o.PlanIds) {
		return true
	}

	return false
}

// SetPlanIds gets a reference to the given []string and assigns it to the PlanIds field.
func (o *OrderCheckoutRequest) SetPlanIds(v []string) {
	o.PlanIds = v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *OrderCheckoutRequest) GetExpiresAt() int64 {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret int64
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCheckoutRequest) GetExpiresAtOk() (*int64, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *OrderCheckoutRequest) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given int64 and assigns it to the ExpiresAt field.
func (o *OrderCheckoutRequest) SetExpiresAt(v int64) {
	o.ExpiresAt = &v
}

// GetFailureUrl returns the FailureUrl field value if set, zero value otherwise.
func (o *OrderCheckoutRequest) GetFailureUrl() string {
	if o == nil || IsNil(o.FailureUrl) {
		var ret string
		return ret
	}
	return *o.FailureUrl
}

// GetFailureUrlOk returns a tuple with the FailureUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCheckoutRequest) GetFailureUrlOk() (*string, bool) {
	if o == nil || IsNil(o.FailureUrl) {
		return nil, false
	}
	return o.FailureUrl, true
}

// HasFailureUrl returns a boolean if a field has been set.
func (o *OrderCheckoutRequest) HasFailureUrl() bool {
	if o != nil && !IsNil(o.FailureUrl) {
		return true
	}

	return false
}

// SetFailureUrl gets a reference to the given string and assigns it to the FailureUrl field.
func (o *OrderCheckoutRequest) SetFailureUrl(v string) {
	o.FailureUrl = &v
}

// GetForceSaveCard returns the ForceSaveCard field value if set, zero value otherwise.
func (o *OrderCheckoutRequest) GetForceSaveCard() bool {
	if o == nil || IsNil(o.ForceSaveCard) {
		var ret bool
		return ret
	}
	return *o.ForceSaveCard
}

// GetForceSaveCardOk returns a tuple with the ForceSaveCard field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCheckoutRequest) GetForceSaveCardOk() (*bool, bool) {
	if o == nil || IsNil(o.ForceSaveCard) {
		return nil, false
	}
	return o.ForceSaveCard, true
}

// HasForceSaveCard returns a boolean if a field has been set.
func (o *OrderCheckoutRequest) HasForceSaveCard() bool {
	if o != nil && !IsNil(o.ForceSaveCard) {
		return true
	}

	return false
}

// SetForceSaveCard gets a reference to the given bool and assigns it to the ForceSaveCard field.
func (o *OrderCheckoutRequest) SetForceSaveCard(v bool) {
	o.ForceSaveCard = &v
}

// GetMonthlyInstallmentsEnabled returns the MonthlyInstallmentsEnabled field value if set, zero value otherwise.
func (o *OrderCheckoutRequest) GetMonthlyInstallmentsEnabled() bool {
	if o == nil || IsNil(o.MonthlyInstallmentsEnabled) {
		var ret bool
		return ret
	}
	return *o.MonthlyInstallmentsEnabled
}

// GetMonthlyInstallmentsEnabledOk returns a tuple with the MonthlyInstallmentsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCheckoutRequest) GetMonthlyInstallmentsEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.MonthlyInstallmentsEnabled) {
		return nil, false
	}
	return o.MonthlyInstallmentsEnabled, true
}

// HasMonthlyInstallmentsEnabled returns a boolean if a field has been set.
func (o *OrderCheckoutRequest) HasMonthlyInstallmentsEnabled() bool {
	if o != nil && !IsNil(o.MonthlyInstallmentsEnabled) {
		return true
	}

	return false
}

// SetMonthlyInstallmentsEnabled gets a reference to the given bool and assigns it to the MonthlyInstallmentsEnabled field.
func (o *OrderCheckoutRequest) SetMonthlyInstallmentsEnabled(v bool) {
	o.MonthlyInstallmentsEnabled = &v
}

// GetMonthlyInstallmentsOptions returns the MonthlyInstallmentsOptions field value if set, zero value otherwise.
func (o *OrderCheckoutRequest) GetMonthlyInstallmentsOptions() []int32 {
	if o == nil || IsNil(o.MonthlyInstallmentsOptions) {
		var ret []int32
		return ret
	}
	return o.MonthlyInstallmentsOptions
}

// GetMonthlyInstallmentsOptionsOk returns a tuple with the MonthlyInstallmentsOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCheckoutRequest) GetMonthlyInstallmentsOptionsOk() ([]int32, bool) {
	if o == nil || IsNil(o.MonthlyInstallmentsOptions) {
		return nil, false
	}
	return o.MonthlyInstallmentsOptions, true
}

// HasMonthlyInstallmentsOptions returns a boolean if a field has been set.
func (o *OrderCheckoutRequest) HasMonthlyInstallmentsOptions() bool {
	if o != nil && !IsNil(o.MonthlyInstallmentsOptions) {
		return true
	}

	return false
}

// SetMonthlyInstallmentsOptions gets a reference to the given []int32 and assigns it to the MonthlyInstallmentsOptions field.
func (o *OrderCheckoutRequest) SetMonthlyInstallmentsOptions(v []int32) {
	o.MonthlyInstallmentsOptions = v
}

// GetMaxFailedRetries returns the MaxFailedRetries field value if set, zero value otherwise.
func (o *OrderCheckoutRequest) GetMaxFailedRetries() int32 {
	if o == nil || IsNil(o.MaxFailedRetries) {
		var ret int32
		return ret
	}
	return *o.MaxFailedRetries
}

// GetMaxFailedRetriesOk returns a tuple with the MaxFailedRetries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCheckoutRequest) GetMaxFailedRetriesOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxFailedRetries) {
		return nil, false
	}
	return o.MaxFailedRetries, true
}

// HasMaxFailedRetries returns a boolean if a field has been set.
func (o *OrderCheckoutRequest) HasMaxFailedRetries() bool {
	if o != nil && !IsNil(o.MaxFailedRetries) {
		return true
	}

	return false
}

// SetMaxFailedRetries gets a reference to the given int32 and assigns it to the MaxFailedRetries field.
func (o *OrderCheckoutRequest) SetMaxFailedRetries(v int32) {
	o.MaxFailedRetries = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OrderCheckoutRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCheckoutRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OrderCheckoutRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OrderCheckoutRequest) SetName(v string) {
	o.Name = &v
}

// GetOnDemandEnabled returns the OnDemandEnabled field value if set, zero value otherwise.
func (o *OrderCheckoutRequest) GetOnDemandEnabled() bool {
	if o == nil || IsNil(o.OnDemandEnabled) {
		var ret bool
		return ret
	}
	return *o.OnDemandEnabled
}

// GetOnDemandEnabledOk returns a tuple with the OnDemandEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCheckoutRequest) GetOnDemandEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.OnDemandEnabled) {
		return nil, false
	}
	return o.OnDemandEnabled, true
}

// HasOnDemandEnabled returns a boolean if a field has been set.
func (o *OrderCheckoutRequest) HasOnDemandEnabled() bool {
	if o != nil && !IsNil(o.OnDemandEnabled) {
		return true
	}

	return false
}

// SetOnDemandEnabled gets a reference to the given bool and assigns it to the OnDemandEnabled field.
func (o *OrderCheckoutRequest) SetOnDemandEnabled(v bool) {
	o.OnDemandEnabled = &v
}

// GetRedirectionTime returns the RedirectionTime field value if set, zero value otherwise.
func (o *OrderCheckoutRequest) GetRedirectionTime() int32 {
	if o == nil || IsNil(o.RedirectionTime) {
		var ret int32
		return ret
	}
	return *o.RedirectionTime
}

// GetRedirectionTimeOk returns a tuple with the RedirectionTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCheckoutRequest) GetRedirectionTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.RedirectionTime) {
		return nil, false
	}
	return o.RedirectionTime, true
}

// HasRedirectionTime returns a boolean if a field has been set.
func (o *OrderCheckoutRequest) HasRedirectionTime() bool {
	if o != nil && !IsNil(o.RedirectionTime) {
		return true
	}

	return false
}

// SetRedirectionTime gets a reference to the given int32 and assigns it to the RedirectionTime field.
func (o *OrderCheckoutRequest) SetRedirectionTime(v int32) {
	o.RedirectionTime = &v
}

// GetSuccessUrl returns the SuccessUrl field value if set, zero value otherwise.
func (o *OrderCheckoutRequest) GetSuccessUrl() string {
	if o == nil || IsNil(o.SuccessUrl) {
		var ret string
		return ret
	}
	return *o.SuccessUrl
}

// GetSuccessUrlOk returns a tuple with the SuccessUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCheckoutRequest) GetSuccessUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SuccessUrl) {
		return nil, false
	}
	return o.SuccessUrl, true
}

// HasSuccessUrl returns a boolean if a field has been set.
func (o *OrderCheckoutRequest) HasSuccessUrl() bool {
	if o != nil && !IsNil(o.SuccessUrl) {
		return true
	}

	return false
}

// SetSuccessUrl gets a reference to the given string and assigns it to the SuccessUrl field.
func (o *OrderCheckoutRequest) SetSuccessUrl(v string) {
	o.SuccessUrl = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *OrderCheckoutRequest) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCheckoutRequest) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *OrderCheckoutRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *OrderCheckoutRequest) SetType(v string) {
	o.Type = &v
}

func (o OrderCheckoutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderCheckoutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AllowedPaymentMethods) {
		toSerialize["allowed_payment_methods"] = o.AllowedPaymentMethods
	}
	if !IsNil(o.ExcludedPaymentMethods) {
		toSerialize["excluded_payment_methods"] = o.ExcludedPaymentMethods
	}
	if !IsNil(o.ExcludeCardNetworks) {
		toSerialize["exclude_card_networks"] = o.ExcludeCardNetworks
	}
	if !IsNil(o.PlanIds) {
		toSerialize["plan_ids"] = o.PlanIds
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	if !IsNil(o.FailureUrl) {
		toSerialize["failure_url"] = o.FailureUrl
	}
	if !IsNil(o.ForceSaveCard) {
		toSerialize["force_save_card"] = o.ForceSaveCard
	}
	if !IsNil(o.MonthlyInstallmentsEnabled) {
		toSerialize["monthly_installments_enabled"] = o.MonthlyInstallmentsEnabled
	}
	if !IsNil(o.MonthlyInstallmentsOptions) {
		toSerialize["monthly_installments_options"] = o.MonthlyInstallmentsOptions
	}
	if !IsNil(o.MaxFailedRetries) {
		toSerialize["max_failed_retries"] = o.MaxFailedRetries
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.OnDemandEnabled) {
		toSerialize["on_demand_enabled"] = o.OnDemandEnabled
	}
	if !IsNil(o.RedirectionTime) {
		toSerialize["redirection_time"] = o.RedirectionTime
	}
	if !IsNil(o.SuccessUrl) {
		toSerialize["success_url"] = o.SuccessUrl
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OrderCheckoutRequest) UnmarshalJSON(data []byte) (err error) {
	varOrderCheckoutRequest := _OrderCheckoutRequest{}

	err = json.Unmarshal(data, &varOrderCheckoutRequest)

	if err != nil {
		return err
	}

	*o = OrderCheckoutRequest(varOrderCheckoutRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "allowed_payment_methods")
		delete(additionalProperties, "excluded_payment_methods")
		delete(additionalProperties, "exclude_card_networks")
		delete(additionalProperties, "plan_ids")
		delete(additionalProperties, "expires_at")
		delete(additionalProperties, "failure_url")
		delete(additionalProperties, "force_save_card")
		delete(additionalProperties, "monthly_installments_enabled")
		delete(additionalProperties, "monthly_installments_options")
		delete(additionalProperties, "max_failed_retries")
		delete(additionalProperties, "name")
		delete(additionalProperties, "on_demand_enabled")
		delete(additionalProperties, "redirection_time")
		delete(additionalProperties, "success_url")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOrderCheckoutRequest struct {
	value *OrderCheckoutRequest
	isSet bool
}

func (v NullableOrderCheckoutRequest) Get() *OrderCheckoutRequest {
	return v.value
}

func (v *NullableOrderCheckoutRequest) Set(val *OrderCheckoutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderCheckoutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderCheckoutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderCheckoutRequest(val *OrderCheckoutRequest) *NullableOrderCheckoutRequest {
	return &NullableOrderCheckoutRequest{value: val, isSet: true}
}

func (v NullableOrderCheckoutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderCheckoutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


