/*
Conekta API

Conekta sdk

API version: 2.3.0
Contact: engineering@conekta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conekta

import (
	"encoding/json"
)

// checks if the UpdateFiscalEntityRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateFiscalEntityRequest{}

// UpdateFiscalEntityRequest struct for UpdateFiscalEntityRequest
type UpdateFiscalEntityRequest struct {
	Address *FiscalEntityRequestAddress `json:"address,omitempty"`
	TaxId *string `json:"tax_id,omitempty"`
	Email *string `json:"email,omitempty"`
	Phone *string `json:"phone,omitempty"`
	Metadata map[string]map[string]interface{} `json:"metadata,omitempty"`
	CompanyName *string `json:"company_name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateFiscalEntityRequest UpdateFiscalEntityRequest

// NewUpdateFiscalEntityRequest instantiates a new UpdateFiscalEntityRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateFiscalEntityRequest() *UpdateFiscalEntityRequest {
	this := UpdateFiscalEntityRequest{}
	return &this
}

// NewUpdateFiscalEntityRequestWithDefaults instantiates a new UpdateFiscalEntityRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateFiscalEntityRequestWithDefaults() *UpdateFiscalEntityRequest {
	this := UpdateFiscalEntityRequest{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *UpdateFiscalEntityRequest) GetAddress() FiscalEntityRequestAddress {
	if o == nil || IsNil(o.Address) {
		var ret FiscalEntityRequestAddress
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFiscalEntityRequest) GetAddressOk() (*FiscalEntityRequestAddress, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *UpdateFiscalEntityRequest) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given FiscalEntityRequestAddress and assigns it to the Address field.
func (o *UpdateFiscalEntityRequest) SetAddress(v FiscalEntityRequestAddress) {
	o.Address = &v
}

// GetTaxId returns the TaxId field value if set, zero value otherwise.
func (o *UpdateFiscalEntityRequest) GetTaxId() string {
	if o == nil || IsNil(o.TaxId) {
		var ret string
		return ret
	}
	return *o.TaxId
}

// GetTaxIdOk returns a tuple with the TaxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFiscalEntityRequest) GetTaxIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaxId) {
		return nil, false
	}
	return o.TaxId, true
}

// HasTaxId returns a boolean if a field has been set.
func (o *UpdateFiscalEntityRequest) HasTaxId() bool {
	if o != nil && !IsNil(o.TaxId) {
		return true
	}

	return false
}

// SetTaxId gets a reference to the given string and assigns it to the TaxId field.
func (o *UpdateFiscalEntityRequest) SetTaxId(v string) {
	o.TaxId = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *UpdateFiscalEntityRequest) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFiscalEntityRequest) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *UpdateFiscalEntityRequest) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *UpdateFiscalEntityRequest) SetEmail(v string) {
	o.Email = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *UpdateFiscalEntityRequest) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFiscalEntityRequest) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *UpdateFiscalEntityRequest) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *UpdateFiscalEntityRequest) SetPhone(v string) {
	o.Phone = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateFiscalEntityRequest) GetMetadata() map[string]map[string]interface{} {
	if o == nil {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateFiscalEntityRequest) GetMetadataOk() (*map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return &o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *UpdateFiscalEntityRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]map[string]interface{} and assigns it to the Metadata field.
func (o *UpdateFiscalEntityRequest) SetMetadata(v map[string]map[string]interface{}) {
	o.Metadata = v
}

// GetCompanyName returns the CompanyName field value if set, zero value otherwise.
func (o *UpdateFiscalEntityRequest) GetCompanyName() string {
	if o == nil || IsNil(o.CompanyName) {
		var ret string
		return ret
	}
	return *o.CompanyName
}

// GetCompanyNameOk returns a tuple with the CompanyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFiscalEntityRequest) GetCompanyNameOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyName) {
		return nil, false
	}
	return o.CompanyName, true
}

// HasCompanyName returns a boolean if a field has been set.
func (o *UpdateFiscalEntityRequest) HasCompanyName() bool {
	if o != nil && !IsNil(o.CompanyName) {
		return true
	}

	return false
}

// SetCompanyName gets a reference to the given string and assigns it to the CompanyName field.
func (o *UpdateFiscalEntityRequest) SetCompanyName(v string) {
	o.CompanyName = &v
}

func (o UpdateFiscalEntityRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateFiscalEntityRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.TaxId) {
		toSerialize["tax_id"] = o.TaxId
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.CompanyName) {
		toSerialize["company_name"] = o.CompanyName
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateFiscalEntityRequest) UnmarshalJSON(data []byte) (err error) {
	varUpdateFiscalEntityRequest := _UpdateFiscalEntityRequest{}

	err = json.Unmarshal(data, &varUpdateFiscalEntityRequest)

	if err != nil {
		return err
	}

	*o = UpdateFiscalEntityRequest(varUpdateFiscalEntityRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "address")
		delete(additionalProperties, "tax_id")
		delete(additionalProperties, "email")
		delete(additionalProperties, "phone")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "company_name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateFiscalEntityRequest struct {
	value *UpdateFiscalEntityRequest
	isSet bool
}

func (v NullableUpdateFiscalEntityRequest) Get() *UpdateFiscalEntityRequest {
	return v.value
}

func (v *NullableUpdateFiscalEntityRequest) Set(val *UpdateFiscalEntityRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateFiscalEntityRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateFiscalEntityRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateFiscalEntityRequest(val *UpdateFiscalEntityRequest) *NullableUpdateFiscalEntityRequest {
	return &NullableUpdateFiscalEntityRequest{value: val, isSet: true}
}

func (v NullableUpdateFiscalEntityRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateFiscalEntityRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


