/*
Conekta API

Conekta sdk

API version: 2.2.0
Contact: engineering@conekta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conekta

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateRuleWhitelistRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRuleWhitelistRequest{}

// CreateRuleWhitelistRequest struct for CreateRuleWhitelistRequest
type CreateRuleWhitelistRequest struct {
	// Description of the rule
	Description string `json:"description"`
	// Field to be used for the rule
	Field string `json:"field"`
	// Value to be used for the rule
	Value string `json:"value"`
	AdditionalProperties map[string]interface{}
}

type _CreateRuleWhitelistRequest CreateRuleWhitelistRequest

// NewCreateRuleWhitelistRequest instantiates a new CreateRuleWhitelistRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRuleWhitelistRequest(description string, field string, value string) *CreateRuleWhitelistRequest {
	this := CreateRuleWhitelistRequest{}
	this.Description = description
	this.Field = field
	this.Value = value
	return &this
}

// NewCreateRuleWhitelistRequestWithDefaults instantiates a new CreateRuleWhitelistRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRuleWhitelistRequestWithDefaults() *CreateRuleWhitelistRequest {
	this := CreateRuleWhitelistRequest{}
	return &this
}

// GetDescription returns the Description field value
func (o *CreateRuleWhitelistRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *CreateRuleWhitelistRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *CreateRuleWhitelistRequest) SetDescription(v string) {
	o.Description = v
}

// GetField returns the Field field value
func (o *CreateRuleWhitelistRequest) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *CreateRuleWhitelistRequest) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *CreateRuleWhitelistRequest) SetField(v string) {
	o.Field = v
}

// GetValue returns the Value field value
func (o *CreateRuleWhitelistRequest) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *CreateRuleWhitelistRequest) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *CreateRuleWhitelistRequest) SetValue(v string) {
	o.Value = v
}

func (o CreateRuleWhitelistRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRuleWhitelistRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	toSerialize["field"] = o.Field
	toSerialize["value"] = o.Value

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateRuleWhitelistRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"field",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateRuleWhitelistRequest := _CreateRuleWhitelistRequest{}

	err = json.Unmarshal(data, &varCreateRuleWhitelistRequest)

	if err != nil {
		return err
	}

	*o = CreateRuleWhitelistRequest(varCreateRuleWhitelistRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "description")
		delete(additionalProperties, "field")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateRuleWhitelistRequest struct {
	value *CreateRuleWhitelistRequest
	isSet bool
}

func (v NullableCreateRuleWhitelistRequest) Get() *CreateRuleWhitelistRequest {
	return v.value
}

func (v *NullableCreateRuleWhitelistRequest) Set(val *CreateRuleWhitelistRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRuleWhitelistRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRuleWhitelistRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRuleWhitelistRequest(val *CreateRuleWhitelistRequest) *NullableCreateRuleWhitelistRequest {
	return &NullableCreateRuleWhitelistRequest{value: val, isSet: true}
}

func (v NullableCreateRuleWhitelistRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRuleWhitelistRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


