/*
Conekta API

Conekta sdk

API version: 2.2.0
Contact: engineering@conekta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conekta

import (
	"encoding/json"
	"fmt"
)

// checks if the OrderFiscalEntityResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderFiscalEntityResponse{}

// OrderFiscalEntityResponse Fiscal entity of the order, Currently it is a purely informative field
type OrderFiscalEntityResponse struct {
	Address OrderFiscalEntityAddressResponse `json:"address"`
	// Email of the fiscal entity
	Email *string `json:"email,omitempty"`
	// Metadata associated with the fiscal entity
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Name of the fiscal entity
	Name *string `json:"name,omitempty"`
	// Tax ID of the fiscal entity
	TaxId *string `json:"tax_id,omitempty"`
	// ID of the fiscal entity
	Id string `json:"id"`
	// The time at which the object was created in seconds since the Unix epoch
	CreatedAt int64 `json:"created_at"`
	Object string `json:"object"`
	// Phone of the fiscal entity
	Phone *string `json:"phone,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OrderFiscalEntityResponse OrderFiscalEntityResponse

// NewOrderFiscalEntityResponse instantiates a new OrderFiscalEntityResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderFiscalEntityResponse(address OrderFiscalEntityAddressResponse, id string, createdAt int64, object string) *OrderFiscalEntityResponse {
	this := OrderFiscalEntityResponse{}
	this.Address = address
	this.Id = id
	this.CreatedAt = createdAt
	this.Object = object
	return &this
}

// NewOrderFiscalEntityResponseWithDefaults instantiates a new OrderFiscalEntityResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderFiscalEntityResponseWithDefaults() *OrderFiscalEntityResponse {
	this := OrderFiscalEntityResponse{}
	return &this
}

// GetAddress returns the Address field value
func (o *OrderFiscalEntityResponse) GetAddress() OrderFiscalEntityAddressResponse {
	if o == nil {
		var ret OrderFiscalEntityAddressResponse
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *OrderFiscalEntityResponse) GetAddressOk() (*OrderFiscalEntityAddressResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *OrderFiscalEntityResponse) SetAddress(v OrderFiscalEntityAddressResponse) {
	o.Address = v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *OrderFiscalEntityResponse) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderFiscalEntityResponse) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *OrderFiscalEntityResponse) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *OrderFiscalEntityResponse) SetEmail(v string) {
	o.Email = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *OrderFiscalEntityResponse) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderFiscalEntityResponse) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *OrderFiscalEntityResponse) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *OrderFiscalEntityResponse) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OrderFiscalEntityResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderFiscalEntityResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OrderFiscalEntityResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OrderFiscalEntityResponse) SetName(v string) {
	o.Name = &v
}

// GetTaxId returns the TaxId field value if set, zero value otherwise.
func (o *OrderFiscalEntityResponse) GetTaxId() string {
	if o == nil || IsNil(o.TaxId) {
		var ret string
		return ret
	}
	return *o.TaxId
}

// GetTaxIdOk returns a tuple with the TaxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderFiscalEntityResponse) GetTaxIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaxId) {
		return nil, false
	}
	return o.TaxId, true
}

// HasTaxId returns a boolean if a field has been set.
func (o *OrderFiscalEntityResponse) HasTaxId() bool {
	if o != nil && !IsNil(o.TaxId) {
		return true
	}

	return false
}

// SetTaxId gets a reference to the given string and assigns it to the TaxId field.
func (o *OrderFiscalEntityResponse) SetTaxId(v string) {
	o.TaxId = &v
}

// GetId returns the Id field value
func (o *OrderFiscalEntityResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OrderFiscalEntityResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OrderFiscalEntityResponse) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *OrderFiscalEntityResponse) GetCreatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *OrderFiscalEntityResponse) GetCreatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *OrderFiscalEntityResponse) SetCreatedAt(v int64) {
	o.CreatedAt = v
}

// GetObject returns the Object field value
func (o *OrderFiscalEntityResponse) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *OrderFiscalEntityResponse) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *OrderFiscalEntityResponse) SetObject(v string) {
	o.Object = v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *OrderFiscalEntityResponse) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderFiscalEntityResponse) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *OrderFiscalEntityResponse) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *OrderFiscalEntityResponse) SetPhone(v string) {
	o.Phone = &v
}

func (o OrderFiscalEntityResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderFiscalEntityResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.TaxId) {
		toSerialize["tax_id"] = o.TaxId
	}
	toSerialize["id"] = o.Id
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["object"] = o.Object
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OrderFiscalEntityResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"id",
		"created_at",
		"object",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrderFiscalEntityResponse := _OrderFiscalEntityResponse{}

	err = json.Unmarshal(data, &varOrderFiscalEntityResponse)

	if err != nil {
		return err
	}

	*o = OrderFiscalEntityResponse(varOrderFiscalEntityResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "address")
		delete(additionalProperties, "email")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "name")
		delete(additionalProperties, "tax_id")
		delete(additionalProperties, "id")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "object")
		delete(additionalProperties, "phone")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOrderFiscalEntityResponse struct {
	value *OrderFiscalEntityResponse
	isSet bool
}

func (v NullableOrderFiscalEntityResponse) Get() *OrderFiscalEntityResponse {
	return v.value
}

func (v *NullableOrderFiscalEntityResponse) Set(val *OrderFiscalEntityResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderFiscalEntityResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderFiscalEntityResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderFiscalEntityResponse(val *OrderFiscalEntityResponse) *NullableOrderFiscalEntityResponse {
	return &NullableOrderFiscalEntityResponse{value: val, isSet: true}
}

func (v NullableOrderFiscalEntityResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderFiscalEntityResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


