/*
Conekta API

Conekta sdk

API version: 2.2.0
Contact: engineering@conekta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conekta

import (
	"encoding/json"
)

// checks if the CreateCompanyRequestBankAccountInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCompanyRequestBankAccountInfo{}

// CreateCompanyRequestBankAccountInfo Bank account information for the company.
type CreateCompanyRequestBankAccountInfo struct {
	// The 18-digit CLABE for the bank account.
	Clabe *string `json:"clabe,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateCompanyRequestBankAccountInfo CreateCompanyRequestBankAccountInfo

// NewCreateCompanyRequestBankAccountInfo instantiates a new CreateCompanyRequestBankAccountInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCompanyRequestBankAccountInfo() *CreateCompanyRequestBankAccountInfo {
	this := CreateCompanyRequestBankAccountInfo{}
	return &this
}

// NewCreateCompanyRequestBankAccountInfoWithDefaults instantiates a new CreateCompanyRequestBankAccountInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCompanyRequestBankAccountInfoWithDefaults() *CreateCompanyRequestBankAccountInfo {
	this := CreateCompanyRequestBankAccountInfo{}
	return &this
}

// GetClabe returns the Clabe field value if set, zero value otherwise.
func (o *CreateCompanyRequestBankAccountInfo) GetClabe() string {
	if o == nil || IsNil(o.Clabe) {
		var ret string
		return ret
	}
	return *o.Clabe
}

// GetClabeOk returns a tuple with the Clabe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCompanyRequestBankAccountInfo) GetClabeOk() (*string, bool) {
	if o == nil || IsNil(o.Clabe) {
		return nil, false
	}
	return o.Clabe, true
}

// HasClabe returns a boolean if a field has been set.
func (o *CreateCompanyRequestBankAccountInfo) HasClabe() bool {
	if o != nil && !IsNil(o.Clabe) {
		return true
	}

	return false
}

// SetClabe gets a reference to the given string and assigns it to the Clabe field.
func (o *CreateCompanyRequestBankAccountInfo) SetClabe(v string) {
	o.Clabe = &v
}

func (o CreateCompanyRequestBankAccountInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCompanyRequestBankAccountInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Clabe) {
		toSerialize["clabe"] = o.Clabe
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateCompanyRequestBankAccountInfo) UnmarshalJSON(data []byte) (err error) {
	varCreateCompanyRequestBankAccountInfo := _CreateCompanyRequestBankAccountInfo{}

	err = json.Unmarshal(data, &varCreateCompanyRequestBankAccountInfo)

	if err != nil {
		return err
	}

	*o = CreateCompanyRequestBankAccountInfo(varCreateCompanyRequestBankAccountInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "clabe")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateCompanyRequestBankAccountInfo struct {
	value *CreateCompanyRequestBankAccountInfo
	isSet bool
}

func (v NullableCreateCompanyRequestBankAccountInfo) Get() *CreateCompanyRequestBankAccountInfo {
	return v.value
}

func (v *NullableCreateCompanyRequestBankAccountInfo) Set(val *CreateCompanyRequestBankAccountInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCompanyRequestBankAccountInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCompanyRequestBankAccountInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCompanyRequestBankAccountInfo(val *CreateCompanyRequestBankAccountInfo) *NullableCreateCompanyRequestBankAccountInfo {
	return &NullableCreateCompanyRequestBankAccountInfo{value: val, isSet: true}
}

func (v NullableCreateCompanyRequestBankAccountInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCompanyRequestBankAccountInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


