/*
Conekta API

Conekta sdk

API version: 2.2.0
Contact: engineering@conekta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conekta

import (
	"encoding/json"
	"fmt"
)

// checks if the OrderShippingLinesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderShippingLinesResponse{}

// OrderShippingLinesResponse List of shipping costs applied to the order
type OrderShippingLinesResponse struct {
	// Indicates if there are more pages to be requested
	HasMore bool `json:"has_more"`
	// Object type, in this case is list
	Object string `json:"object"`
	// URL of the next page.
	NextPageUrl *string `json:"next_page_url,omitempty"`
	// Url of the previous page.
	PreviousPageUrl *string `json:"previous_page_url,omitempty"`
	Data []ShippingLinesDataResponse `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OrderShippingLinesResponse OrderShippingLinesResponse

// NewOrderShippingLinesResponse instantiates a new OrderShippingLinesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderShippingLinesResponse(hasMore bool, object string) *OrderShippingLinesResponse {
	this := OrderShippingLinesResponse{}
	this.HasMore = hasMore
	this.Object = object
	return &this
}

// NewOrderShippingLinesResponseWithDefaults instantiates a new OrderShippingLinesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderShippingLinesResponseWithDefaults() *OrderShippingLinesResponse {
	this := OrderShippingLinesResponse{}
	return &this
}

// GetHasMore returns the HasMore field value
func (o *OrderShippingLinesResponse) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *OrderShippingLinesResponse) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *OrderShippingLinesResponse) SetHasMore(v bool) {
	o.HasMore = v
}

// GetObject returns the Object field value
func (o *OrderShippingLinesResponse) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *OrderShippingLinesResponse) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *OrderShippingLinesResponse) SetObject(v string) {
	o.Object = v
}

// GetNextPageUrl returns the NextPageUrl field value if set, zero value otherwise.
func (o *OrderShippingLinesResponse) GetNextPageUrl() string {
	if o == nil || IsNil(o.NextPageUrl) {
		var ret string
		return ret
	}
	return *o.NextPageUrl
}

// GetNextPageUrlOk returns a tuple with the NextPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderShippingLinesResponse) GetNextPageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageUrl) {
		return nil, false
	}
	return o.NextPageUrl, true
}

// HasNextPageUrl returns a boolean if a field has been set.
func (o *OrderShippingLinesResponse) HasNextPageUrl() bool {
	if o != nil && !IsNil(o.NextPageUrl) {
		return true
	}

	return false
}

// SetNextPageUrl gets a reference to the given string and assigns it to the NextPageUrl field.
func (o *OrderShippingLinesResponse) SetNextPageUrl(v string) {
	o.NextPageUrl = &v
}

// GetPreviousPageUrl returns the PreviousPageUrl field value if set, zero value otherwise.
func (o *OrderShippingLinesResponse) GetPreviousPageUrl() string {
	if o == nil || IsNil(o.PreviousPageUrl) {
		var ret string
		return ret
	}
	return *o.PreviousPageUrl
}

// GetPreviousPageUrlOk returns a tuple with the PreviousPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderShippingLinesResponse) GetPreviousPageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.PreviousPageUrl) {
		return nil, false
	}
	return o.PreviousPageUrl, true
}

// HasPreviousPageUrl returns a boolean if a field has been set.
func (o *OrderShippingLinesResponse) HasPreviousPageUrl() bool {
	if o != nil && !IsNil(o.PreviousPageUrl) {
		return true
	}

	return false
}

// SetPreviousPageUrl gets a reference to the given string and assigns it to the PreviousPageUrl field.
func (o *OrderShippingLinesResponse) SetPreviousPageUrl(v string) {
	o.PreviousPageUrl = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *OrderShippingLinesResponse) GetData() []ShippingLinesDataResponse {
	if o == nil || IsNil(o.Data) {
		var ret []ShippingLinesDataResponse
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderShippingLinesResponse) GetDataOk() ([]ShippingLinesDataResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *OrderShippingLinesResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ShippingLinesDataResponse and assigns it to the Data field.
func (o *OrderShippingLinesResponse) SetData(v []ShippingLinesDataResponse) {
	o.Data = v
}

func (o OrderShippingLinesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderShippingLinesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["has_more"] = o.HasMore
	toSerialize["object"] = o.Object
	if !IsNil(o.NextPageUrl) {
		toSerialize["next_page_url"] = o.NextPageUrl
	}
	if !IsNil(o.PreviousPageUrl) {
		toSerialize["previous_page_url"] = o.PreviousPageUrl
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OrderShippingLinesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"has_more",
		"object",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrderShippingLinesResponse := _OrderShippingLinesResponse{}

	err = json.Unmarshal(data, &varOrderShippingLinesResponse)

	if err != nil {
		return err
	}

	*o = OrderShippingLinesResponse(varOrderShippingLinesResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "has_more")
		delete(additionalProperties, "object")
		delete(additionalProperties, "next_page_url")
		delete(additionalProperties, "previous_page_url")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOrderShippingLinesResponse struct {
	value *OrderShippingLinesResponse
	isSet bool
}

func (v NullableOrderShippingLinesResponse) Get() *OrderShippingLinesResponse {
	return v.value
}

func (v *NullableOrderShippingLinesResponse) Set(val *OrderShippingLinesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderShippingLinesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderShippingLinesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderShippingLinesResponse(val *OrderShippingLinesResponse) *NullableOrderShippingLinesResponse {
	return &NullableOrderShippingLinesResponse{value: val, isSet: true}
}

func (v NullableOrderShippingLinesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderShippingLinesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


