/*
Conekta API

Conekta sdk

API version: 2.3.0
Contact: engineering@conekta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conekta

import (
	"encoding/json"
	"fmt"
)

// checks if the LogResponseForRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LogResponseForRequest{}

// LogResponseForRequest log model
type LogResponseForRequest struct {
	CreatedAt int64 `json:"created_at"`
	Id string `json:"id"`
	IpAddress *string `json:"ip_address,omitempty"`
	Livemode bool `json:"livemode"`
	LoggableId *string `json:"loggable_id,omitempty"`
	LoggableType *string `json:"loggable_type,omitempty"`
	Method *string `json:"method,omitempty"`
	OauthTokenId *string `json:"oauth_token_id,omitempty"`
	QueryString map[string]interface{} `json:"query_string,omitempty"`
	Related *string `json:"related,omitempty"`
	RequestBody map[string]interface{} `json:"request_body,omitempty"`
	RequestHeaders map[string]string `json:"request_headers,omitempty"`
	ResponseBody map[string]interface{} `json:"response_body,omitempty"`
	ResponseHeaders map[string]string `json:"response_headers,omitempty"`
	SearchableTags []string `json:"searchable_tags,omitempty"`
	Status *string `json:"status,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	Url *string `json:"url,omitempty"`
	UserAccountId *string `json:"user_account_id,omitempty"`
	Version *string `json:"version,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LogResponseForRequest LogResponseForRequest

// NewLogResponseForRequest instantiates a new LogResponseForRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogResponseForRequest(createdAt int64, id string, livemode bool) *LogResponseForRequest {
	this := LogResponseForRequest{}
	this.CreatedAt = createdAt
	this.Id = id
	this.Livemode = livemode
	return &this
}

// NewLogResponseForRequestWithDefaults instantiates a new LogResponseForRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLogResponseForRequestWithDefaults() *LogResponseForRequest {
	this := LogResponseForRequest{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *LogResponseForRequest) GetCreatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *LogResponseForRequest) GetCreatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *LogResponseForRequest) SetCreatedAt(v int64) {
	o.CreatedAt = v
}

// GetId returns the Id field value
func (o *LogResponseForRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *LogResponseForRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *LogResponseForRequest) SetId(v string) {
	o.Id = v
}

// GetIpAddress returns the IpAddress field value if set, zero value otherwise.
func (o *LogResponseForRequest) GetIpAddress() string {
	if o == nil || IsNil(o.IpAddress) {
		var ret string
		return ret
	}
	return *o.IpAddress
}

// GetIpAddressOk returns a tuple with the IpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogResponseForRequest) GetIpAddressOk() (*string, bool) {
	if o == nil || IsNil(o.IpAddress) {
		return nil, false
	}
	return o.IpAddress, true
}

// HasIpAddress returns a boolean if a field has been set.
func (o *LogResponseForRequest) HasIpAddress() bool {
	if o != nil && !IsNil(o.IpAddress) {
		return true
	}

	return false
}

// SetIpAddress gets a reference to the given string and assigns it to the IpAddress field.
func (o *LogResponseForRequest) SetIpAddress(v string) {
	o.IpAddress = &v
}

// GetLivemode returns the Livemode field value
func (o *LogResponseForRequest) GetLivemode() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Livemode
}

// GetLivemodeOk returns a tuple with the Livemode field value
// and a boolean to check if the value has been set.
func (o *LogResponseForRequest) GetLivemodeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Livemode, true
}

// SetLivemode sets field value
func (o *LogResponseForRequest) SetLivemode(v bool) {
	o.Livemode = v
}

// GetLoggableId returns the LoggableId field value if set, zero value otherwise.
func (o *LogResponseForRequest) GetLoggableId() string {
	if o == nil || IsNil(o.LoggableId) {
		var ret string
		return ret
	}
	return *o.LoggableId
}

// GetLoggableIdOk returns a tuple with the LoggableId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogResponseForRequest) GetLoggableIdOk() (*string, bool) {
	if o == nil || IsNil(o.LoggableId) {
		return nil, false
	}
	return o.LoggableId, true
}

// HasLoggableId returns a boolean if a field has been set.
func (o *LogResponseForRequest) HasLoggableId() bool {
	if o != nil && !IsNil(o.LoggableId) {
		return true
	}

	return false
}

// SetLoggableId gets a reference to the given string and assigns it to the LoggableId field.
func (o *LogResponseForRequest) SetLoggableId(v string) {
	o.LoggableId = &v
}

// GetLoggableType returns the LoggableType field value if set, zero value otherwise.
func (o *LogResponseForRequest) GetLoggableType() string {
	if o == nil || IsNil(o.LoggableType) {
		var ret string
		return ret
	}
	return *o.LoggableType
}

// GetLoggableTypeOk returns a tuple with the LoggableType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogResponseForRequest) GetLoggableTypeOk() (*string, bool) {
	if o == nil || IsNil(o.LoggableType) {
		return nil, false
	}
	return o.LoggableType, true
}

// HasLoggableType returns a boolean if a field has been set.
func (o *LogResponseForRequest) HasLoggableType() bool {
	if o != nil && !IsNil(o.LoggableType) {
		return true
	}

	return false
}

// SetLoggableType gets a reference to the given string and assigns it to the LoggableType field.
func (o *LogResponseForRequest) SetLoggableType(v string) {
	o.LoggableType = &v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *LogResponseForRequest) GetMethod() string {
	if o == nil || IsNil(o.Method) {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogResponseForRequest) GetMethodOk() (*string, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *LogResponseForRequest) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *LogResponseForRequest) SetMethod(v string) {
	o.Method = &v
}

// GetOauthTokenId returns the OauthTokenId field value if set, zero value otherwise.
func (o *LogResponseForRequest) GetOauthTokenId() string {
	if o == nil || IsNil(o.OauthTokenId) {
		var ret string
		return ret
	}
	return *o.OauthTokenId
}

// GetOauthTokenIdOk returns a tuple with the OauthTokenId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogResponseForRequest) GetOauthTokenIdOk() (*string, bool) {
	if o == nil || IsNil(o.OauthTokenId) {
		return nil, false
	}
	return o.OauthTokenId, true
}

// HasOauthTokenId returns a boolean if a field has been set.
func (o *LogResponseForRequest) HasOauthTokenId() bool {
	if o != nil && !IsNil(o.OauthTokenId) {
		return true
	}

	return false
}

// SetOauthTokenId gets a reference to the given string and assigns it to the OauthTokenId field.
func (o *LogResponseForRequest) SetOauthTokenId(v string) {
	o.OauthTokenId = &v
}

// GetQueryString returns the QueryString field value if set, zero value otherwise.
func (o *LogResponseForRequest) GetQueryString() map[string]interface{} {
	if o == nil || IsNil(o.QueryString) {
		var ret map[string]interface{}
		return ret
	}
	return o.QueryString
}

// GetQueryStringOk returns a tuple with the QueryString field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogResponseForRequest) GetQueryStringOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.QueryString) {
		return map[string]interface{}{}, false
	}
	return o.QueryString, true
}

// HasQueryString returns a boolean if a field has been set.
func (o *LogResponseForRequest) HasQueryString() bool {
	if o != nil && !IsNil(o.QueryString) {
		return true
	}

	return false
}

// SetQueryString gets a reference to the given map[string]interface{} and assigns it to the QueryString field.
func (o *LogResponseForRequest) SetQueryString(v map[string]interface{}) {
	o.QueryString = v
}

// GetRelated returns the Related field value if set, zero value otherwise.
func (o *LogResponseForRequest) GetRelated() string {
	if o == nil || IsNil(o.Related) {
		var ret string
		return ret
	}
	return *o.Related
}

// GetRelatedOk returns a tuple with the Related field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogResponseForRequest) GetRelatedOk() (*string, bool) {
	if o == nil || IsNil(o.Related) {
		return nil, false
	}
	return o.Related, true
}

// HasRelated returns a boolean if a field has been set.
func (o *LogResponseForRequest) HasRelated() bool {
	if o != nil && !IsNil(o.Related) {
		return true
	}

	return false
}

// SetRelated gets a reference to the given string and assigns it to the Related field.
func (o *LogResponseForRequest) SetRelated(v string) {
	o.Related = &v
}

// GetRequestBody returns the RequestBody field value if set, zero value otherwise.
func (o *LogResponseForRequest) GetRequestBody() map[string]interface{} {
	if o == nil || IsNil(o.RequestBody) {
		var ret map[string]interface{}
		return ret
	}
	return o.RequestBody
}

// GetRequestBodyOk returns a tuple with the RequestBody field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogResponseForRequest) GetRequestBodyOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.RequestBody) {
		return map[string]interface{}{}, false
	}
	return o.RequestBody, true
}

// HasRequestBody returns a boolean if a field has been set.
func (o *LogResponseForRequest) HasRequestBody() bool {
	if o != nil && !IsNil(o.RequestBody) {
		return true
	}

	return false
}

// SetRequestBody gets a reference to the given map[string]interface{} and assigns it to the RequestBody field.
func (o *LogResponseForRequest) SetRequestBody(v map[string]interface{}) {
	o.RequestBody = v
}

// GetRequestHeaders returns the RequestHeaders field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LogResponseForRequest) GetRequestHeaders() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}
	return o.RequestHeaders
}

// GetRequestHeadersOk returns a tuple with the RequestHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LogResponseForRequest) GetRequestHeadersOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.RequestHeaders) {
		return nil, false
	}
	return &o.RequestHeaders, true
}

// HasRequestHeaders returns a boolean if a field has been set.
func (o *LogResponseForRequest) HasRequestHeaders() bool {
	if o != nil && !IsNil(o.RequestHeaders) {
		return true
	}

	return false
}

// SetRequestHeaders gets a reference to the given map[string]string and assigns it to the RequestHeaders field.
func (o *LogResponseForRequest) SetRequestHeaders(v map[string]string) {
	o.RequestHeaders = v
}

// GetResponseBody returns the ResponseBody field value if set, zero value otherwise.
func (o *LogResponseForRequest) GetResponseBody() map[string]interface{} {
	if o == nil || IsNil(o.ResponseBody) {
		var ret map[string]interface{}
		return ret
	}
	return o.ResponseBody
}

// GetResponseBodyOk returns a tuple with the ResponseBody field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogResponseForRequest) GetResponseBodyOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ResponseBody) {
		return map[string]interface{}{}, false
	}
	return o.ResponseBody, true
}

// HasResponseBody returns a boolean if a field has been set.
func (o *LogResponseForRequest) HasResponseBody() bool {
	if o != nil && !IsNil(o.ResponseBody) {
		return true
	}

	return false
}

// SetResponseBody gets a reference to the given map[string]interface{} and assigns it to the ResponseBody field.
func (o *LogResponseForRequest) SetResponseBody(v map[string]interface{}) {
	o.ResponseBody = v
}

// GetResponseHeaders returns the ResponseHeaders field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LogResponseForRequest) GetResponseHeaders() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}
	return o.ResponseHeaders
}

// GetResponseHeadersOk returns a tuple with the ResponseHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LogResponseForRequest) GetResponseHeadersOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.ResponseHeaders) {
		return nil, false
	}
	return &o.ResponseHeaders, true
}

// HasResponseHeaders returns a boolean if a field has been set.
func (o *LogResponseForRequest) HasResponseHeaders() bool {
	if o != nil && !IsNil(o.ResponseHeaders) {
		return true
	}

	return false
}

// SetResponseHeaders gets a reference to the given map[string]string and assigns it to the ResponseHeaders field.
func (o *LogResponseForRequest) SetResponseHeaders(v map[string]string) {
	o.ResponseHeaders = v
}

// GetSearchableTags returns the SearchableTags field value if set, zero value otherwise.
func (o *LogResponseForRequest) GetSearchableTags() []string {
	if o == nil || IsNil(o.SearchableTags) {
		var ret []string
		return ret
	}
	return o.SearchableTags
}

// GetSearchableTagsOk returns a tuple with the SearchableTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogResponseForRequest) GetSearchableTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.SearchableTags) {
		return nil, false
	}
	return o.SearchableTags, true
}

// HasSearchableTags returns a boolean if a field has been set.
func (o *LogResponseForRequest) HasSearchableTags() bool {
	if o != nil && !IsNil(o.SearchableTags) {
		return true
	}

	return false
}

// SetSearchableTags gets a reference to the given []string and assigns it to the SearchableTags field.
func (o *LogResponseForRequest) SetSearchableTags(v []string) {
	o.SearchableTags = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *LogResponseForRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogResponseForRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *LogResponseForRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *LogResponseForRequest) SetStatus(v string) {
	o.Status = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *LogResponseForRequest) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogResponseForRequest) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *LogResponseForRequest) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *LogResponseForRequest) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *LogResponseForRequest) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogResponseForRequest) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *LogResponseForRequest) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *LogResponseForRequest) SetUrl(v string) {
	o.Url = &v
}

// GetUserAccountId returns the UserAccountId field value if set, zero value otherwise.
func (o *LogResponseForRequest) GetUserAccountId() string {
	if o == nil || IsNil(o.UserAccountId) {
		var ret string
		return ret
	}
	return *o.UserAccountId
}

// GetUserAccountIdOk returns a tuple with the UserAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogResponseForRequest) GetUserAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserAccountId) {
		return nil, false
	}
	return o.UserAccountId, true
}

// HasUserAccountId returns a boolean if a field has been set.
func (o *LogResponseForRequest) HasUserAccountId() bool {
	if o != nil && !IsNil(o.UserAccountId) {
		return true
	}

	return false
}

// SetUserAccountId gets a reference to the given string and assigns it to the UserAccountId field.
func (o *LogResponseForRequest) SetUserAccountId(v string) {
	o.UserAccountId = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *LogResponseForRequest) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogResponseForRequest) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *LogResponseForRequest) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *LogResponseForRequest) SetVersion(v string) {
	o.Version = &v
}

func (o LogResponseForRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LogResponseForRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["id"] = o.Id
	if !IsNil(o.IpAddress) {
		toSerialize["ip_address"] = o.IpAddress
	}
	toSerialize["livemode"] = o.Livemode
	if !IsNil(o.LoggableId) {
		toSerialize["loggable_id"] = o.LoggableId
	}
	if !IsNil(o.LoggableType) {
		toSerialize["loggable_type"] = o.LoggableType
	}
	if !IsNil(o.Method) {
		toSerialize["method"] = o.Method
	}
	if !IsNil(o.OauthTokenId) {
		toSerialize["oauth_token_id"] = o.OauthTokenId
	}
	if !IsNil(o.QueryString) {
		toSerialize["query_string"] = o.QueryString
	}
	if !IsNil(o.Related) {
		toSerialize["related"] = o.Related
	}
	if !IsNil(o.RequestBody) {
		toSerialize["request_body"] = o.RequestBody
	}
	if o.RequestHeaders != nil {
		toSerialize["request_headers"] = o.RequestHeaders
	}
	if !IsNil(o.ResponseBody) {
		toSerialize["response_body"] = o.ResponseBody
	}
	if o.ResponseHeaders != nil {
		toSerialize["response_headers"] = o.ResponseHeaders
	}
	if !IsNil(o.SearchableTags) {
		toSerialize["searchable_tags"] = o.SearchableTags
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.UserAccountId) {
		toSerialize["user_account_id"] = o.UserAccountId
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LogResponseForRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"id",
		"livemode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLogResponseForRequest := _LogResponseForRequest{}

	err = json.Unmarshal(data, &varLogResponseForRequest)

	if err != nil {
		return err
	}

	*o = LogResponseForRequest(varLogResponseForRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "id")
		delete(additionalProperties, "ip_address")
		delete(additionalProperties, "livemode")
		delete(additionalProperties, "loggable_id")
		delete(additionalProperties, "loggable_type")
		delete(additionalProperties, "method")
		delete(additionalProperties, "oauth_token_id")
		delete(additionalProperties, "query_string")
		delete(additionalProperties, "related")
		delete(additionalProperties, "request_body")
		delete(additionalProperties, "request_headers")
		delete(additionalProperties, "response_body")
		delete(additionalProperties, "response_headers")
		delete(additionalProperties, "searchable_tags")
		delete(additionalProperties, "status")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "url")
		delete(additionalProperties, "user_account_id")
		delete(additionalProperties, "version")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLogResponseForRequest struct {
	value *LogResponseForRequest
	isSet bool
}

func (v NullableLogResponseForRequest) Get() *LogResponseForRequest {
	return v.value
}

func (v *NullableLogResponseForRequest) Set(val *LogResponseForRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLogResponseForRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLogResponseForRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogResponseForRequest(val *LogResponseForRequest) *NullableLogResponseForRequest {
	return &NullableLogResponseForRequest{value: val, isSet: true}
}

func (v NullableLogResponseForRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogResponseForRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


