/*
Conekta API

Conekta sdk

API version: 2.2.0
Contact: engineering@conekta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conekta

import (
	"encoding/json"
)

// checks if the CustomerUpdateShippingContactsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerUpdateShippingContactsRequest{}

// CustomerUpdateShippingContactsRequest [Shipping](https://developers.conekta.com/v2.2.0/reference/createcustomershippingcontacts) details, required in case of sending a shipping. If we do not receive a shipping_contact on the order, the default shipping_contact of the customer will be used.
type CustomerUpdateShippingContactsRequest struct {
	// Phone contact
	Phone *string `json:"phone,omitempty"`
	// Name of the person who will receive the order
	Receiver *string `json:"receiver,omitempty"`
	// The street names between which the order will be delivered.
	BetweenStreets *string `json:"between_streets,omitempty"`
	Address *CustomerShippingContactsRequestAddress `json:"address,omitempty"`
	ParentId *string `json:"parent_id,omitempty"`
	Default *bool `json:"default,omitempty"`
	Deleted *bool `json:"deleted,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CustomerUpdateShippingContactsRequest CustomerUpdateShippingContactsRequest

// NewCustomerUpdateShippingContactsRequest instantiates a new CustomerUpdateShippingContactsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerUpdateShippingContactsRequest() *CustomerUpdateShippingContactsRequest {
	this := CustomerUpdateShippingContactsRequest{}
	return &this
}

// NewCustomerUpdateShippingContactsRequestWithDefaults instantiates a new CustomerUpdateShippingContactsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerUpdateShippingContactsRequestWithDefaults() *CustomerUpdateShippingContactsRequest {
	this := CustomerUpdateShippingContactsRequest{}
	return &this
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *CustomerUpdateShippingContactsRequest) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerUpdateShippingContactsRequest) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *CustomerUpdateShippingContactsRequest) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *CustomerUpdateShippingContactsRequest) SetPhone(v string) {
	o.Phone = &v
}

// GetReceiver returns the Receiver field value if set, zero value otherwise.
func (o *CustomerUpdateShippingContactsRequest) GetReceiver() string {
	if o == nil || IsNil(o.Receiver) {
		var ret string
		return ret
	}
	return *o.Receiver
}

// GetReceiverOk returns a tuple with the Receiver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerUpdateShippingContactsRequest) GetReceiverOk() (*string, bool) {
	if o == nil || IsNil(o.Receiver) {
		return nil, false
	}
	return o.Receiver, true
}

// HasReceiver returns a boolean if a field has been set.
func (o *CustomerUpdateShippingContactsRequest) HasReceiver() bool {
	if o != nil && !IsNil(o.Receiver) {
		return true
	}

	return false
}

// SetReceiver gets a reference to the given string and assigns it to the Receiver field.
func (o *CustomerUpdateShippingContactsRequest) SetReceiver(v string) {
	o.Receiver = &v
}

// GetBetweenStreets returns the BetweenStreets field value if set, zero value otherwise.
func (o *CustomerUpdateShippingContactsRequest) GetBetweenStreets() string {
	if o == nil || IsNil(o.BetweenStreets) {
		var ret string
		return ret
	}
	return *o.BetweenStreets
}

// GetBetweenStreetsOk returns a tuple with the BetweenStreets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerUpdateShippingContactsRequest) GetBetweenStreetsOk() (*string, bool) {
	if o == nil || IsNil(o.BetweenStreets) {
		return nil, false
	}
	return o.BetweenStreets, true
}

// HasBetweenStreets returns a boolean if a field has been set.
func (o *CustomerUpdateShippingContactsRequest) HasBetweenStreets() bool {
	if o != nil && !IsNil(o.BetweenStreets) {
		return true
	}

	return false
}

// SetBetweenStreets gets a reference to the given string and assigns it to the BetweenStreets field.
func (o *CustomerUpdateShippingContactsRequest) SetBetweenStreets(v string) {
	o.BetweenStreets = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *CustomerUpdateShippingContactsRequest) GetAddress() CustomerShippingContactsRequestAddress {
	if o == nil || IsNil(o.Address) {
		var ret CustomerShippingContactsRequestAddress
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerUpdateShippingContactsRequest) GetAddressOk() (*CustomerShippingContactsRequestAddress, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *CustomerUpdateShippingContactsRequest) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given CustomerShippingContactsRequestAddress and assigns it to the Address field.
func (o *CustomerUpdateShippingContactsRequest) SetAddress(v CustomerShippingContactsRequestAddress) {
	o.Address = &v
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *CustomerUpdateShippingContactsRequest) GetParentId() string {
	if o == nil || IsNil(o.ParentId) {
		var ret string
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerUpdateShippingContactsRequest) GetParentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentId) {
		return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *CustomerUpdateShippingContactsRequest) HasParentId() bool {
	if o != nil && !IsNil(o.ParentId) {
		return true
	}

	return false
}

// SetParentId gets a reference to the given string and assigns it to the ParentId field.
func (o *CustomerUpdateShippingContactsRequest) SetParentId(v string) {
	o.ParentId = &v
}

// GetDefault returns the Default field value if set, zero value otherwise.
func (o *CustomerUpdateShippingContactsRequest) GetDefault() bool {
	if o == nil || IsNil(o.Default) {
		var ret bool
		return ret
	}
	return *o.Default
}

// GetDefaultOk returns a tuple with the Default field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerUpdateShippingContactsRequest) GetDefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.Default) {
		return nil, false
	}
	return o.Default, true
}

// HasDefault returns a boolean if a field has been set.
func (o *CustomerUpdateShippingContactsRequest) HasDefault() bool {
	if o != nil && !IsNil(o.Default) {
		return true
	}

	return false
}

// SetDefault gets a reference to the given bool and assigns it to the Default field.
func (o *CustomerUpdateShippingContactsRequest) SetDefault(v bool) {
	o.Default = &v
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *CustomerUpdateShippingContactsRequest) GetDeleted() bool {
	if o == nil || IsNil(o.Deleted) {
		var ret bool
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerUpdateShippingContactsRequest) GetDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deleted) {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *CustomerUpdateShippingContactsRequest) HasDeleted() bool {
	if o != nil && !IsNil(o.Deleted) {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given bool and assigns it to the Deleted field.
func (o *CustomerUpdateShippingContactsRequest) SetDeleted(v bool) {
	o.Deleted = &v
}

func (o CustomerUpdateShippingContactsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerUpdateShippingContactsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if !IsNil(o.Receiver) {
		toSerialize["receiver"] = o.Receiver
	}
	if !IsNil(o.BetweenStreets) {
		toSerialize["between_streets"] = o.BetweenStreets
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.ParentId) {
		toSerialize["parent_id"] = o.ParentId
	}
	if !IsNil(o.Default) {
		toSerialize["default"] = o.Default
	}
	if !IsNil(o.Deleted) {
		toSerialize["deleted"] = o.Deleted
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomerUpdateShippingContactsRequest) UnmarshalJSON(data []byte) (err error) {
	varCustomerUpdateShippingContactsRequest := _CustomerUpdateShippingContactsRequest{}

	err = json.Unmarshal(data, &varCustomerUpdateShippingContactsRequest)

	if err != nil {
		return err
	}

	*o = CustomerUpdateShippingContactsRequest(varCustomerUpdateShippingContactsRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "phone")
		delete(additionalProperties, "receiver")
		delete(additionalProperties, "between_streets")
		delete(additionalProperties, "address")
		delete(additionalProperties, "parent_id")
		delete(additionalProperties, "default")
		delete(additionalProperties, "deleted")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCustomerUpdateShippingContactsRequest struct {
	value *CustomerUpdateShippingContactsRequest
	isSet bool
}

func (v NullableCustomerUpdateShippingContactsRequest) Get() *CustomerUpdateShippingContactsRequest {
	return v.value
}

func (v *NullableCustomerUpdateShippingContactsRequest) Set(val *CustomerUpdateShippingContactsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerUpdateShippingContactsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerUpdateShippingContactsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerUpdateShippingContactsRequest(val *CustomerUpdateShippingContactsRequest) *NullableCustomerUpdateShippingContactsRequest {
	return &NullableCustomerUpdateShippingContactsRequest{value: val, isSet: true}
}

func (v NullableCustomerUpdateShippingContactsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerUpdateShippingContactsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


