/*
Conekta API

Conekta sdk

API version: 2.1.0
Contact: engineering@conekta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conekta

import (
	"encoding/json"
	"fmt"
)

// checks if the ChargesOrderResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChargesOrderResponse{}

// ChargesOrderResponse The charges associated with the order
type ChargesOrderResponse struct {
	// Indicates if there are more pages to be requested
	HasMore bool `json:"has_more"`
	// Object type, in this case is list
	Object string `json:"object"`
	Data []ChargesOrderResponseAllOfData `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ChargesOrderResponse ChargesOrderResponse

// NewChargesOrderResponse instantiates a new ChargesOrderResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChargesOrderResponse(hasMore bool, object string) *ChargesOrderResponse {
	this := ChargesOrderResponse{}
	this.HasMore = hasMore
	this.Object = object
	return &this
}

// NewChargesOrderResponseWithDefaults instantiates a new ChargesOrderResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChargesOrderResponseWithDefaults() *ChargesOrderResponse {
	this := ChargesOrderResponse{}
	return &this
}

// GetHasMore returns the HasMore field value
func (o *ChargesOrderResponse) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *ChargesOrderResponse) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *ChargesOrderResponse) SetHasMore(v bool) {
	o.HasMore = v
}

// GetObject returns the Object field value
func (o *ChargesOrderResponse) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *ChargesOrderResponse) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *ChargesOrderResponse) SetObject(v string) {
	o.Object = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ChargesOrderResponse) GetData() []ChargesOrderResponseAllOfData {
	if o == nil || IsNil(o.Data) {
		var ret []ChargesOrderResponseAllOfData
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChargesOrderResponse) GetDataOk() ([]ChargesOrderResponseAllOfData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ChargesOrderResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ChargesOrderResponseAllOfData and assigns it to the Data field.
func (o *ChargesOrderResponse) SetData(v []ChargesOrderResponseAllOfData) {
	o.Data = v
}

func (o ChargesOrderResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChargesOrderResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["has_more"] = o.HasMore
	toSerialize["object"] = o.Object
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ChargesOrderResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"has_more",
		"object",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChargesOrderResponse := _ChargesOrderResponse{}

	err = json.Unmarshal(data, &varChargesOrderResponse)

	if err != nil {
		return err
	}

	*o = ChargesOrderResponse(varChargesOrderResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "has_more")
		delete(additionalProperties, "object")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableChargesOrderResponse struct {
	value *ChargesOrderResponse
	isSet bool
}

func (v NullableChargesOrderResponse) Get() *ChargesOrderResponse {
	return v.value
}

func (v *NullableChargesOrderResponse) Set(val *ChargesOrderResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableChargesOrderResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableChargesOrderResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChargesOrderResponse(val *ChargesOrderResponse) *NullableChargesOrderResponse {
	return &NullableChargesOrderResponse{value: val, isSet: true}
}

func (v NullableChargesOrderResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChargesOrderResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


