/*
Conekta API

Conekta sdk

API version: 2.2.0
Contact: engineering@conekta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conekta

import (
	"encoding/json"
	"fmt"
)

// checks if the CustomerInfoCustomerId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerInfoCustomerId{}

// CustomerInfoCustomerId struct for CustomerInfoCustomerId
type CustomerInfoCustomerId struct {
	CustomerId string `json:"customer_id"`
	AdditionalProperties map[string]interface{}
}

type _CustomerInfoCustomerId CustomerInfoCustomerId

// NewCustomerInfoCustomerId instantiates a new CustomerInfoCustomerId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerInfoCustomerId(customerId string) *CustomerInfoCustomerId {
	this := CustomerInfoCustomerId{}
	this.CustomerId = customerId
	return &this
}

// NewCustomerInfoCustomerIdWithDefaults instantiates a new CustomerInfoCustomerId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerInfoCustomerIdWithDefaults() *CustomerInfoCustomerId {
	this := CustomerInfoCustomerId{}
	return &this
}

// GetCustomerId returns the CustomerId field value
func (o *CustomerInfoCustomerId) GetCustomerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
func (o *CustomerInfoCustomerId) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerId, true
}

// SetCustomerId sets field value
func (o *CustomerInfoCustomerId) SetCustomerId(v string) {
	o.CustomerId = v
}

func (o CustomerInfoCustomerId) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerInfoCustomerId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["customer_id"] = o.CustomerId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomerInfoCustomerId) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"customer_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomerInfoCustomerId := _CustomerInfoCustomerId{}

	err = json.Unmarshal(data, &varCustomerInfoCustomerId)

	if err != nil {
		return err
	}

	*o = CustomerInfoCustomerId(varCustomerInfoCustomerId)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "customer_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCustomerInfoCustomerId struct {
	value *CustomerInfoCustomerId
	isSet bool
}

func (v NullableCustomerInfoCustomerId) Get() *CustomerInfoCustomerId {
	return v.value
}

func (v *NullableCustomerInfoCustomerId) Set(val *CustomerInfoCustomerId) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerInfoCustomerId) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerInfoCustomerId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerInfoCustomerId(val *CustomerInfoCustomerId) *NullableCustomerInfoCustomerId {
	return &NullableCustomerInfoCustomerId{value: val, isSet: true}
}

func (v NullableCustomerInfoCustomerId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerInfoCustomerId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


