/*
Conekta API

Conekta sdk

API version: 2.2.0
Contact: engineering@conekta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conekta

import (
	"encoding/json"
	"fmt"
)

// checks if the PayoutOrderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PayoutOrderRequest{}

// PayoutOrderRequest a payout order
type PayoutOrderRequest struct {
	// The payout methods that are allowed for the payout order.
	AllowedPayoutMethods []string `json:"allowed_payout_methods"`
	// The amount of the payout order.
	Amount int64 `json:"amount"`
	// The currency in which the payout order is made.
	Currency string `json:"currency"`
	CustomerInfo PayoutOrderRequestCustomerInfo `json:"customer_info"`
	// The expiration time of the payout order in Unix timestamp.
	ExpiresAt int64 `json:"expires_at"`
	// The metadata of the payout order.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Payout Payout `json:"payout"`
	// The reason for the payout order.
	Reason string `json:"reason"`
	AdditionalProperties map[string]interface{}
}

type _PayoutOrderRequest PayoutOrderRequest

// NewPayoutOrderRequest instantiates a new PayoutOrderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPayoutOrderRequest(allowedPayoutMethods []string, amount int64, currency string, customerInfo PayoutOrderRequestCustomerInfo, expiresAt int64, payout Payout, reason string) *PayoutOrderRequest {
	this := PayoutOrderRequest{}
	this.AllowedPayoutMethods = allowedPayoutMethods
	this.Amount = amount
	this.Currency = currency
	this.CustomerInfo = customerInfo
	this.ExpiresAt = expiresAt
	this.Payout = payout
	this.Reason = reason
	return &this
}

// NewPayoutOrderRequestWithDefaults instantiates a new PayoutOrderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPayoutOrderRequestWithDefaults() *PayoutOrderRequest {
	this := PayoutOrderRequest{}
	var currency string = "MXN"
	this.Currency = currency
	return &this
}

// GetAllowedPayoutMethods returns the AllowedPayoutMethods field value
func (o *PayoutOrderRequest) GetAllowedPayoutMethods() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AllowedPayoutMethods
}

// GetAllowedPayoutMethodsOk returns a tuple with the AllowedPayoutMethods field value
// and a boolean to check if the value has been set.
func (o *PayoutOrderRequest) GetAllowedPayoutMethodsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AllowedPayoutMethods, true
}

// SetAllowedPayoutMethods sets field value
func (o *PayoutOrderRequest) SetAllowedPayoutMethods(v []string) {
	o.AllowedPayoutMethods = v
}

// GetAmount returns the Amount field value
func (o *PayoutOrderRequest) GetAmount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *PayoutOrderRequest) GetAmountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *PayoutOrderRequest) SetAmount(v int64) {
	o.Amount = v
}

// GetCurrency returns the Currency field value
func (o *PayoutOrderRequest) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *PayoutOrderRequest) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *PayoutOrderRequest) SetCurrency(v string) {
	o.Currency = v
}

// GetCustomerInfo returns the CustomerInfo field value
func (o *PayoutOrderRequest) GetCustomerInfo() PayoutOrderRequestCustomerInfo {
	if o == nil {
		var ret PayoutOrderRequestCustomerInfo
		return ret
	}

	return o.CustomerInfo
}

// GetCustomerInfoOk returns a tuple with the CustomerInfo field value
// and a boolean to check if the value has been set.
func (o *PayoutOrderRequest) GetCustomerInfoOk() (*PayoutOrderRequestCustomerInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerInfo, true
}

// SetCustomerInfo sets field value
func (o *PayoutOrderRequest) SetCustomerInfo(v PayoutOrderRequestCustomerInfo) {
	o.CustomerInfo = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *PayoutOrderRequest) GetExpiresAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *PayoutOrderRequest) GetExpiresAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *PayoutOrderRequest) SetExpiresAt(v int64) {
	o.ExpiresAt = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *PayoutOrderRequest) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayoutOrderRequest) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *PayoutOrderRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *PayoutOrderRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetPayout returns the Payout field value
func (o *PayoutOrderRequest) GetPayout() Payout {
	if o == nil {
		var ret Payout
		return ret
	}

	return o.Payout
}

// GetPayoutOk returns a tuple with the Payout field value
// and a boolean to check if the value has been set.
func (o *PayoutOrderRequest) GetPayoutOk() (*Payout, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Payout, true
}

// SetPayout sets field value
func (o *PayoutOrderRequest) SetPayout(v Payout) {
	o.Payout = v
}

// GetReason returns the Reason field value
func (o *PayoutOrderRequest) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *PayoutOrderRequest) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *PayoutOrderRequest) SetReason(v string) {
	o.Reason = v
}

func (o PayoutOrderRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PayoutOrderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["allowed_payout_methods"] = o.AllowedPayoutMethods
	toSerialize["amount"] = o.Amount
	toSerialize["currency"] = o.Currency
	toSerialize["customer_info"] = o.CustomerInfo
	toSerialize["expires_at"] = o.ExpiresAt
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["payout"] = o.Payout
	toSerialize["reason"] = o.Reason

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PayoutOrderRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"allowed_payout_methods",
		"amount",
		"currency",
		"customer_info",
		"expires_at",
		"payout",
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPayoutOrderRequest := _PayoutOrderRequest{}

	err = json.Unmarshal(data, &varPayoutOrderRequest)

	if err != nil {
		return err
	}

	*o = PayoutOrderRequest(varPayoutOrderRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "allowed_payout_methods")
		delete(additionalProperties, "amount")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "customer_info")
		delete(additionalProperties, "expires_at")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "payout")
		delete(additionalProperties, "reason")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePayoutOrderRequest struct {
	value *PayoutOrderRequest
	isSet bool
}

func (v NullablePayoutOrderRequest) Get() *PayoutOrderRequest {
	return v.value
}

func (v *NullablePayoutOrderRequest) Set(val *PayoutOrderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePayoutOrderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePayoutOrderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePayoutOrderRequest(val *PayoutOrderRequest) *NullablePayoutOrderRequest {
	return &NullablePayoutOrderRequest{value: val, isSet: true}
}

func (v NullablePayoutOrderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePayoutOrderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


