/*
Conekta API

Conekta sdk

API version: 2.2.0
Contact: engineering@conekta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conekta

import (
	"encoding/json"
	"fmt"
)

// checks if the PaymentMethodPbbPayment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentMethodPbbPayment{}

// PaymentMethodPbbPayment struct for PaymentMethodPbbPayment
type PaymentMethodPbbPayment struct {
	Type *string `json:"type,omitempty"`
	Object string `json:"object"`
	// Deep link for the payment, use for mobile apps/flows
	DeepLink string `json:"deep_link"`
	// Expiration date of the charge
	ExpiresAt int64 `json:"expires_at"`
	// Product type of the charge
	ProductType string `json:"product_type"`
	// URL to redirect the customer to complete the payment
	RedirectUrl string `json:"redirect_url"`
	// Reference for the payment
	Reference string `json:"reference"`
	AdditionalProperties map[string]interface{}
}

type _PaymentMethodPbbPayment PaymentMethodPbbPayment

// NewPaymentMethodPbbPayment instantiates a new PaymentMethodPbbPayment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentMethodPbbPayment(object string, deepLink string, expiresAt int64, productType string, redirectUrl string, reference string) *PaymentMethodPbbPayment {
	this := PaymentMethodPbbPayment{}
	this.Object = object
	this.DeepLink = deepLink
	this.ExpiresAt = expiresAt
	this.ProductType = productType
	this.RedirectUrl = redirectUrl
	this.Reference = reference
	return &this
}

// NewPaymentMethodPbbPaymentWithDefaults instantiates a new PaymentMethodPbbPayment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentMethodPbbPaymentWithDefaults() *PaymentMethodPbbPayment {
	this := PaymentMethodPbbPayment{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *PaymentMethodPbbPayment) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentMethodPbbPayment) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *PaymentMethodPbbPayment) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *PaymentMethodPbbPayment) SetType(v string) {
	o.Type = &v
}

// GetObject returns the Object field value
func (o *PaymentMethodPbbPayment) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodPbbPayment) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *PaymentMethodPbbPayment) SetObject(v string) {
	o.Object = v
}

// GetDeepLink returns the DeepLink field value
func (o *PaymentMethodPbbPayment) GetDeepLink() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeepLink
}

// GetDeepLinkOk returns a tuple with the DeepLink field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodPbbPayment) GetDeepLinkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeepLink, true
}

// SetDeepLink sets field value
func (o *PaymentMethodPbbPayment) SetDeepLink(v string) {
	o.DeepLink = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *PaymentMethodPbbPayment) GetExpiresAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodPbbPayment) GetExpiresAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *PaymentMethodPbbPayment) SetExpiresAt(v int64) {
	o.ExpiresAt = v
}

// GetProductType returns the ProductType field value
func (o *PaymentMethodPbbPayment) GetProductType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProductType
}

// GetProductTypeOk returns a tuple with the ProductType field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodPbbPayment) GetProductTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductType, true
}

// SetProductType sets field value
func (o *PaymentMethodPbbPayment) SetProductType(v string) {
	o.ProductType = v
}

// GetRedirectUrl returns the RedirectUrl field value
func (o *PaymentMethodPbbPayment) GetRedirectUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RedirectUrl
}

// GetRedirectUrlOk returns a tuple with the RedirectUrl field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodPbbPayment) GetRedirectUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RedirectUrl, true
}

// SetRedirectUrl sets field value
func (o *PaymentMethodPbbPayment) SetRedirectUrl(v string) {
	o.RedirectUrl = v
}

// GetReference returns the Reference field value
func (o *PaymentMethodPbbPayment) GetReference() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodPbbPayment) GetReferenceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reference, true
}

// SetReference sets field value
func (o *PaymentMethodPbbPayment) SetReference(v string) {
	o.Reference = v
}

func (o PaymentMethodPbbPayment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentMethodPbbPayment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	toSerialize["object"] = o.Object
	toSerialize["deep_link"] = o.DeepLink
	toSerialize["expires_at"] = o.ExpiresAt
	toSerialize["product_type"] = o.ProductType
	toSerialize["redirect_url"] = o.RedirectUrl
	toSerialize["reference"] = o.Reference

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaymentMethodPbbPayment) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object",
		"deep_link",
		"expires_at",
		"product_type",
		"redirect_url",
		"reference",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentMethodPbbPayment := _PaymentMethodPbbPayment{}

	err = json.Unmarshal(data, &varPaymentMethodPbbPayment)

	if err != nil {
		return err
	}

	*o = PaymentMethodPbbPayment(varPaymentMethodPbbPayment)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "object")
		delete(additionalProperties, "deep_link")
		delete(additionalProperties, "expires_at")
		delete(additionalProperties, "product_type")
		delete(additionalProperties, "redirect_url")
		delete(additionalProperties, "reference")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaymentMethodPbbPayment struct {
	value *PaymentMethodPbbPayment
	isSet bool
}

func (v NullablePaymentMethodPbbPayment) Get() *PaymentMethodPbbPayment {
	return v.value
}

func (v *NullablePaymentMethodPbbPayment) Set(val *PaymentMethodPbbPayment) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentMethodPbbPayment) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentMethodPbbPayment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentMethodPbbPayment(val *PaymentMethodPbbPayment) *NullablePaymentMethodPbbPayment {
	return &NullablePaymentMethodPbbPayment{value: val, isSet: true}
}

func (v NullablePaymentMethodPbbPayment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentMethodPbbPayment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


