/*
Conekta API

Conekta sdk

API version: 2.2.0
Contact: engineering@conekta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conekta

import (
	"encoding/json"
	"fmt"
)

// checks if the ShippingLinesDataResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShippingLinesDataResponse{}

// ShippingLinesDataResponse struct for ShippingLinesDataResponse
type ShippingLinesDataResponse struct {
	// Shipping amount in cents
	Amount int64 `json:"amount"`
	// Carrier name for the shipment
	Carrier *string `json:"carrier,omitempty"`
	// Tracking number can be used to track the shipment
	TrackingNumber *string `json:"tracking_number,omitempty"`
	// Method of shipment
	Method *string `json:"method,omitempty"`
	// Hash where the user can send additional information for each 'shipping'.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Id *string `json:"id,omitempty"`
	Object *string `json:"object,omitempty"`
	ParentId *string `json:"parent_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ShippingLinesDataResponse ShippingLinesDataResponse

// NewShippingLinesDataResponse instantiates a new ShippingLinesDataResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShippingLinesDataResponse(amount int64) *ShippingLinesDataResponse {
	this := ShippingLinesDataResponse{}
	this.Amount = amount
	return &this
}

// NewShippingLinesDataResponseWithDefaults instantiates a new ShippingLinesDataResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShippingLinesDataResponseWithDefaults() *ShippingLinesDataResponse {
	this := ShippingLinesDataResponse{}
	return &this
}

// GetAmount returns the Amount field value
func (o *ShippingLinesDataResponse) GetAmount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *ShippingLinesDataResponse) GetAmountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *ShippingLinesDataResponse) SetAmount(v int64) {
	o.Amount = v
}

// GetCarrier returns the Carrier field value if set, zero value otherwise.
func (o *ShippingLinesDataResponse) GetCarrier() string {
	if o == nil || IsNil(o.Carrier) {
		var ret string
		return ret
	}
	return *o.Carrier
}

// GetCarrierOk returns a tuple with the Carrier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingLinesDataResponse) GetCarrierOk() (*string, bool) {
	if o == nil || IsNil(o.Carrier) {
		return nil, false
	}
	return o.Carrier, true
}

// HasCarrier returns a boolean if a field has been set.
func (o *ShippingLinesDataResponse) HasCarrier() bool {
	if o != nil && !IsNil(o.Carrier) {
		return true
	}

	return false
}

// SetCarrier gets a reference to the given string and assigns it to the Carrier field.
func (o *ShippingLinesDataResponse) SetCarrier(v string) {
	o.Carrier = &v
}

// GetTrackingNumber returns the TrackingNumber field value if set, zero value otherwise.
func (o *ShippingLinesDataResponse) GetTrackingNumber() string {
	if o == nil || IsNil(o.TrackingNumber) {
		var ret string
		return ret
	}
	return *o.TrackingNumber
}

// GetTrackingNumberOk returns a tuple with the TrackingNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingLinesDataResponse) GetTrackingNumberOk() (*string, bool) {
	if o == nil || IsNil(o.TrackingNumber) {
		return nil, false
	}
	return o.TrackingNumber, true
}

// HasTrackingNumber returns a boolean if a field has been set.
func (o *ShippingLinesDataResponse) HasTrackingNumber() bool {
	if o != nil && !IsNil(o.TrackingNumber) {
		return true
	}

	return false
}

// SetTrackingNumber gets a reference to the given string and assigns it to the TrackingNumber field.
func (o *ShippingLinesDataResponse) SetTrackingNumber(v string) {
	o.TrackingNumber = &v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *ShippingLinesDataResponse) GetMethod() string {
	if o == nil || IsNil(o.Method) {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingLinesDataResponse) GetMethodOk() (*string, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *ShippingLinesDataResponse) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *ShippingLinesDataResponse) SetMethod(v string) {
	o.Method = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ShippingLinesDataResponse) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingLinesDataResponse) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ShippingLinesDataResponse) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *ShippingLinesDataResponse) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ShippingLinesDataResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingLinesDataResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ShippingLinesDataResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ShippingLinesDataResponse) SetId(v string) {
	o.Id = &v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *ShippingLinesDataResponse) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingLinesDataResponse) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *ShippingLinesDataResponse) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *ShippingLinesDataResponse) SetObject(v string) {
	o.Object = &v
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *ShippingLinesDataResponse) GetParentId() string {
	if o == nil || IsNil(o.ParentId) {
		var ret string
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingLinesDataResponse) GetParentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentId) {
		return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *ShippingLinesDataResponse) HasParentId() bool {
	if o != nil && !IsNil(o.ParentId) {
		return true
	}

	return false
}

// SetParentId gets a reference to the given string and assigns it to the ParentId field.
func (o *ShippingLinesDataResponse) SetParentId(v string) {
	o.ParentId = &v
}

func (o ShippingLinesDataResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShippingLinesDataResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amount"] = o.Amount
	if !IsNil(o.Carrier) {
		toSerialize["carrier"] = o.Carrier
	}
	if !IsNil(o.TrackingNumber) {
		toSerialize["tracking_number"] = o.TrackingNumber
	}
	if !IsNil(o.Method) {
		toSerialize["method"] = o.Method
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	if !IsNil(o.ParentId) {
		toSerialize["parent_id"] = o.ParentId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ShippingLinesDataResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varShippingLinesDataResponse := _ShippingLinesDataResponse{}

	err = json.Unmarshal(data, &varShippingLinesDataResponse)

	if err != nil {
		return err
	}

	*o = ShippingLinesDataResponse(varShippingLinesDataResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "amount")
		delete(additionalProperties, "carrier")
		delete(additionalProperties, "tracking_number")
		delete(additionalProperties, "method")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "id")
		delete(additionalProperties, "object")
		delete(additionalProperties, "parent_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableShippingLinesDataResponse struct {
	value *ShippingLinesDataResponse
	isSet bool
}

func (v NullableShippingLinesDataResponse) Get() *ShippingLinesDataResponse {
	return v.value
}

func (v *NullableShippingLinesDataResponse) Set(val *ShippingLinesDataResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableShippingLinesDataResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableShippingLinesDataResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShippingLinesDataResponse(val *ShippingLinesDataResponse) *NullableShippingLinesDataResponse {
	return &NullableShippingLinesDataResponse{value: val, isSet: true}
}

func (v NullableShippingLinesDataResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShippingLinesDataResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


