/*
Conekta API

Conekta sdk

API version: 2.2.0
Contact: engineering@conekta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conekta

import (
	"encoding/json"
)

// checks if the SubscriptionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionResponse{}

// SubscriptionResponse subscription model
type SubscriptionResponse struct {
	BillingCycleStart *int64 `json:"billing_cycle_start,omitempty"`
	BillingCycleEnd *int64 `json:"billing_cycle_end,omitempty"`
	CanceledAt *int64 `json:"canceled_at,omitempty"`
	// Reason for cancellation. This field appears when the subscription status is 'canceled'.
	CanceledReason *string `json:"canceled_reason,omitempty"`
	CardId *string `json:"card_id,omitempty"`
	ChargeId *string `json:"charge_id,omitempty"`
	CreatedAt *int64 `json:"created_at,omitempty"`
	CustomerCustomReference *string `json:"customer_custom_reference,omitempty"`
	CustomerId *string `json:"customer_id,omitempty"`
	Id *string `json:"id,omitempty"`
	LastBillingCycleOrderId *string `json:"last_billing_cycle_order_id,omitempty"`
	Object *string `json:"object,omitempty"`
	PausedAt *int64 `json:"paused_at,omitempty"`
	PlanId *string `json:"plan_id,omitempty"`
	Status *string `json:"status,omitempty"`
	SubscriptionStart *int32 `json:"subscription_start,omitempty"`
	TrialStart *int64 `json:"trial_start,omitempty"`
	TrialEnd *int64 `json:"trial_end,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SubscriptionResponse SubscriptionResponse

// NewSubscriptionResponse instantiates a new SubscriptionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionResponse() *SubscriptionResponse {
	this := SubscriptionResponse{}
	return &this
}

// NewSubscriptionResponseWithDefaults instantiates a new SubscriptionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionResponseWithDefaults() *SubscriptionResponse {
	this := SubscriptionResponse{}
	return &this
}

// GetBillingCycleStart returns the BillingCycleStart field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetBillingCycleStart() int64 {
	if o == nil || IsNil(o.BillingCycleStart) {
		var ret int64
		return ret
	}
	return *o.BillingCycleStart
}

// GetBillingCycleStartOk returns a tuple with the BillingCycleStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetBillingCycleStartOk() (*int64, bool) {
	if o == nil || IsNil(o.BillingCycleStart) {
		return nil, false
	}
	return o.BillingCycleStart, true
}

// HasBillingCycleStart returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasBillingCycleStart() bool {
	if o != nil && !IsNil(o.BillingCycleStart) {
		return true
	}

	return false
}

// SetBillingCycleStart gets a reference to the given int64 and assigns it to the BillingCycleStart field.
func (o *SubscriptionResponse) SetBillingCycleStart(v int64) {
	o.BillingCycleStart = &v
}

// GetBillingCycleEnd returns the BillingCycleEnd field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetBillingCycleEnd() int64 {
	if o == nil || IsNil(o.BillingCycleEnd) {
		var ret int64
		return ret
	}
	return *o.BillingCycleEnd
}

// GetBillingCycleEndOk returns a tuple with the BillingCycleEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetBillingCycleEndOk() (*int64, bool) {
	if o == nil || IsNil(o.BillingCycleEnd) {
		return nil, false
	}
	return o.BillingCycleEnd, true
}

// HasBillingCycleEnd returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasBillingCycleEnd() bool {
	if o != nil && !IsNil(o.BillingCycleEnd) {
		return true
	}

	return false
}

// SetBillingCycleEnd gets a reference to the given int64 and assigns it to the BillingCycleEnd field.
func (o *SubscriptionResponse) SetBillingCycleEnd(v int64) {
	o.BillingCycleEnd = &v
}

// GetCanceledAt returns the CanceledAt field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetCanceledAt() int64 {
	if o == nil || IsNil(o.CanceledAt) {
		var ret int64
		return ret
	}
	return *o.CanceledAt
}

// GetCanceledAtOk returns a tuple with the CanceledAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetCanceledAtOk() (*int64, bool) {
	if o == nil || IsNil(o.CanceledAt) {
		return nil, false
	}
	return o.CanceledAt, true
}

// HasCanceledAt returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasCanceledAt() bool {
	if o != nil && !IsNil(o.CanceledAt) {
		return true
	}

	return false
}

// SetCanceledAt gets a reference to the given int64 and assigns it to the CanceledAt field.
func (o *SubscriptionResponse) SetCanceledAt(v int64) {
	o.CanceledAt = &v
}

// GetCanceledReason returns the CanceledReason field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetCanceledReason() string {
	if o == nil || IsNil(o.CanceledReason) {
		var ret string
		return ret
	}
	return *o.CanceledReason
}

// GetCanceledReasonOk returns a tuple with the CanceledReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetCanceledReasonOk() (*string, bool) {
	if o == nil || IsNil(o.CanceledReason) {
		return nil, false
	}
	return o.CanceledReason, true
}

// HasCanceledReason returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasCanceledReason() bool {
	if o != nil && !IsNil(o.CanceledReason) {
		return true
	}

	return false
}

// SetCanceledReason gets a reference to the given string and assigns it to the CanceledReason field.
func (o *SubscriptionResponse) SetCanceledReason(v string) {
	o.CanceledReason = &v
}

// GetCardId returns the CardId field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetCardId() string {
	if o == nil || IsNil(o.CardId) {
		var ret string
		return ret
	}
	return *o.CardId
}

// GetCardIdOk returns a tuple with the CardId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetCardIdOk() (*string, bool) {
	if o == nil || IsNil(o.CardId) {
		return nil, false
	}
	return o.CardId, true
}

// HasCardId returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasCardId() bool {
	if o != nil && !IsNil(o.CardId) {
		return true
	}

	return false
}

// SetCardId gets a reference to the given string and assigns it to the CardId field.
func (o *SubscriptionResponse) SetCardId(v string) {
	o.CardId = &v
}

// GetChargeId returns the ChargeId field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetChargeId() string {
	if o == nil || IsNil(o.ChargeId) {
		var ret string
		return ret
	}
	return *o.ChargeId
}

// GetChargeIdOk returns a tuple with the ChargeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetChargeIdOk() (*string, bool) {
	if o == nil || IsNil(o.ChargeId) {
		return nil, false
	}
	return o.ChargeId, true
}

// HasChargeId returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasChargeId() bool {
	if o != nil && !IsNil(o.ChargeId) {
		return true
	}

	return false
}

// SetChargeId gets a reference to the given string and assigns it to the ChargeId field.
func (o *SubscriptionResponse) SetChargeId(v string) {
	o.ChargeId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetCreatedAt() int64 {
	if o == nil || IsNil(o.CreatedAt) {
		var ret int64
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetCreatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int64 and assigns it to the CreatedAt field.
func (o *SubscriptionResponse) SetCreatedAt(v int64) {
	o.CreatedAt = &v
}

// GetCustomerCustomReference returns the CustomerCustomReference field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetCustomerCustomReference() string {
	if o == nil || IsNil(o.CustomerCustomReference) {
		var ret string
		return ret
	}
	return *o.CustomerCustomReference
}

// GetCustomerCustomReferenceOk returns a tuple with the CustomerCustomReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetCustomerCustomReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerCustomReference) {
		return nil, false
	}
	return o.CustomerCustomReference, true
}

// HasCustomerCustomReference returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasCustomerCustomReference() bool {
	if o != nil && !IsNil(o.CustomerCustomReference) {
		return true
	}

	return false
}

// SetCustomerCustomReference gets a reference to the given string and assigns it to the CustomerCustomReference field.
func (o *SubscriptionResponse) SetCustomerCustomReference(v string) {
	o.CustomerCustomReference = &v
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *SubscriptionResponse) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SubscriptionResponse) SetId(v string) {
	o.Id = &v
}

// GetLastBillingCycleOrderId returns the LastBillingCycleOrderId field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetLastBillingCycleOrderId() string {
	if o == nil || IsNil(o.LastBillingCycleOrderId) {
		var ret string
		return ret
	}
	return *o.LastBillingCycleOrderId
}

// GetLastBillingCycleOrderIdOk returns a tuple with the LastBillingCycleOrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetLastBillingCycleOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.LastBillingCycleOrderId) {
		return nil, false
	}
	return o.LastBillingCycleOrderId, true
}

// HasLastBillingCycleOrderId returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasLastBillingCycleOrderId() bool {
	if o != nil && !IsNil(o.LastBillingCycleOrderId) {
		return true
	}

	return false
}

// SetLastBillingCycleOrderId gets a reference to the given string and assigns it to the LastBillingCycleOrderId field.
func (o *SubscriptionResponse) SetLastBillingCycleOrderId(v string) {
	o.LastBillingCycleOrderId = &v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *SubscriptionResponse) SetObject(v string) {
	o.Object = &v
}

// GetPausedAt returns the PausedAt field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetPausedAt() int64 {
	if o == nil || IsNil(o.PausedAt) {
		var ret int64
		return ret
	}
	return *o.PausedAt
}

// GetPausedAtOk returns a tuple with the PausedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetPausedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.PausedAt) {
		return nil, false
	}
	return o.PausedAt, true
}

// HasPausedAt returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasPausedAt() bool {
	if o != nil && !IsNil(o.PausedAt) {
		return true
	}

	return false
}

// SetPausedAt gets a reference to the given int64 and assigns it to the PausedAt field.
func (o *SubscriptionResponse) SetPausedAt(v int64) {
	o.PausedAt = &v
}

// GetPlanId returns the PlanId field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetPlanId() string {
	if o == nil || IsNil(o.PlanId) {
		var ret string
		return ret
	}
	return *o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetPlanIdOk() (*string, bool) {
	if o == nil || IsNil(o.PlanId) {
		return nil, false
	}
	return o.PlanId, true
}

// HasPlanId returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasPlanId() bool {
	if o != nil && !IsNil(o.PlanId) {
		return true
	}

	return false
}

// SetPlanId gets a reference to the given string and assigns it to the PlanId field.
func (o *SubscriptionResponse) SetPlanId(v string) {
	o.PlanId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *SubscriptionResponse) SetStatus(v string) {
	o.Status = &v
}

// GetSubscriptionStart returns the SubscriptionStart field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetSubscriptionStart() int32 {
	if o == nil || IsNil(o.SubscriptionStart) {
		var ret int32
		return ret
	}
	return *o.SubscriptionStart
}

// GetSubscriptionStartOk returns a tuple with the SubscriptionStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetSubscriptionStartOk() (*int32, bool) {
	if o == nil || IsNil(o.SubscriptionStart) {
		return nil, false
	}
	return o.SubscriptionStart, true
}

// HasSubscriptionStart returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasSubscriptionStart() bool {
	if o != nil && !IsNil(o.SubscriptionStart) {
		return true
	}

	return false
}

// SetSubscriptionStart gets a reference to the given int32 and assigns it to the SubscriptionStart field.
func (o *SubscriptionResponse) SetSubscriptionStart(v int32) {
	o.SubscriptionStart = &v
}

// GetTrialStart returns the TrialStart field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetTrialStart() int64 {
	if o == nil || IsNil(o.TrialStart) {
		var ret int64
		return ret
	}
	return *o.TrialStart
}

// GetTrialStartOk returns a tuple with the TrialStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetTrialStartOk() (*int64, bool) {
	if o == nil || IsNil(o.TrialStart) {
		return nil, false
	}
	return o.TrialStart, true
}

// HasTrialStart returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasTrialStart() bool {
	if o != nil && !IsNil(o.TrialStart) {
		return true
	}

	return false
}

// SetTrialStart gets a reference to the given int64 and assigns it to the TrialStart field.
func (o *SubscriptionResponse) SetTrialStart(v int64) {
	o.TrialStart = &v
}

// GetTrialEnd returns the TrialEnd field value if set, zero value otherwise.
func (o *SubscriptionResponse) GetTrialEnd() int64 {
	if o == nil || IsNil(o.TrialEnd) {
		var ret int64
		return ret
	}
	return *o.TrialEnd
}

// GetTrialEndOk returns a tuple with the TrialEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionResponse) GetTrialEndOk() (*int64, bool) {
	if o == nil || IsNil(o.TrialEnd) {
		return nil, false
	}
	return o.TrialEnd, true
}

// HasTrialEnd returns a boolean if a field has been set.
func (o *SubscriptionResponse) HasTrialEnd() bool {
	if o != nil && !IsNil(o.TrialEnd) {
		return true
	}

	return false
}

// SetTrialEnd gets a reference to the given int64 and assigns it to the TrialEnd field.
func (o *SubscriptionResponse) SetTrialEnd(v int64) {
	o.TrialEnd = &v
}

func (o SubscriptionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BillingCycleStart) {
		toSerialize["billing_cycle_start"] = o.BillingCycleStart
	}
	if !IsNil(o.BillingCycleEnd) {
		toSerialize["billing_cycle_end"] = o.BillingCycleEnd
	}
	if !IsNil(o.CanceledAt) {
		toSerialize["canceled_at"] = o.CanceledAt
	}
	if !IsNil(o.CanceledReason) {
		toSerialize["canceled_reason"] = o.CanceledReason
	}
	if !IsNil(o.CardId) {
		toSerialize["card_id"] = o.CardId
	}
	if !IsNil(o.ChargeId) {
		toSerialize["charge_id"] = o.ChargeId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.CustomerCustomReference) {
		toSerialize["customer_custom_reference"] = o.CustomerCustomReference
	}
	if !IsNil(o.CustomerId) {
		toSerialize["customer_id"] = o.CustomerId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LastBillingCycleOrderId) {
		toSerialize["last_billing_cycle_order_id"] = o.LastBillingCycleOrderId
	}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	if !IsNil(o.PausedAt) {
		toSerialize["paused_at"] = o.PausedAt
	}
	if !IsNil(o.PlanId) {
		toSerialize["plan_id"] = o.PlanId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.SubscriptionStart) {
		toSerialize["subscription_start"] = o.SubscriptionStart
	}
	if !IsNil(o.TrialStart) {
		toSerialize["trial_start"] = o.TrialStart
	}
	if !IsNil(o.TrialEnd) {
		toSerialize["trial_end"] = o.TrialEnd
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SubscriptionResponse) UnmarshalJSON(data []byte) (err error) {
	varSubscriptionResponse := _SubscriptionResponse{}

	err = json.Unmarshal(data, &varSubscriptionResponse)

	if err != nil {
		return err
	}

	*o = SubscriptionResponse(varSubscriptionResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "billing_cycle_start")
		delete(additionalProperties, "billing_cycle_end")
		delete(additionalProperties, "canceled_at")
		delete(additionalProperties, "canceled_reason")
		delete(additionalProperties, "card_id")
		delete(additionalProperties, "charge_id")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "customer_custom_reference")
		delete(additionalProperties, "customer_id")
		delete(additionalProperties, "id")
		delete(additionalProperties, "last_billing_cycle_order_id")
		delete(additionalProperties, "object")
		delete(additionalProperties, "paused_at")
		delete(additionalProperties, "plan_id")
		delete(additionalProperties, "status")
		delete(additionalProperties, "subscription_start")
		delete(additionalProperties, "trial_start")
		delete(additionalProperties, "trial_end")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSubscriptionResponse struct {
	value *SubscriptionResponse
	isSet bool
}

func (v NullableSubscriptionResponse) Get() *SubscriptionResponse {
	return v.value
}

func (v *NullableSubscriptionResponse) Set(val *SubscriptionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionResponse(val *SubscriptionResponse) *NullableSubscriptionResponse {
	return &NullableSubscriptionResponse{value: val, isSet: true}
}

func (v NullableSubscriptionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


