name: Golang CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  tests:
    strategy:
      matrix:
        sdk: [1.16, 1.17, 1.18, 1.19, 1.20.x]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.sdk }}
      - name: Install dependencies
        run: git config --global url."ssh://git@github.com/conekta".insteadOf https://github.com/conekta && go mod download -x
      - name: Build
        run: go build -v ./...
      - uses: actions/setup-node@v2
      - name: Install Mockserver
        run: |
          npm install -g @mockoon/cli
          npx mockoon-cli start --data https://raw.githubusercontent.com/conekta/openapi/acaa935a9eed5b7c3a49b681bd801bcfa501cc5a/mocks/conekta_api.json --port 3000
      - name: Run tests
        run: go test -v --race ./...
        env:
          BASE_PATH: localhost:3000
