name: Golang CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
permissions:
  contents: read
jobs:
  tests:
    strategy:
      matrix:
        sdk: [1.16, 1.17, 1.18, 1.19, 1.20.x, 1.21.x]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.sdk }}
      - name: Run Mockoon CLI
        uses: mockoon/cli-action@v3
        with:
          version: 'latest'
          data-file: 'https://raw.githubusercontent.com/conekta/openapi/main/mocks/conekta_api.json'
          port: 3000
      - name: Run tests
        run: |
          go test -v --race ./...
        env:
          BASE_PATH: localhost:3000
